### ISSUE TITLE
After setting NACOS_AUTH_ENABLE=true, the request return 403 

### ISSUE THREAD

**Issue by catcherwong** [nacos-group/nacos-sdk-csharp#1]
from https://github.com/catcherwong/nacos-sdk-csharp/issues/32   @wangengzheng

----
nacos-docker 开启权限认证之后 accessToken 放在header并没有通过认证 而是需要放在 querystring才通过

java代码那边我看了下暂时没找到认证体系代码

GET http://192.168.15.44:10211/nacos/v1/cs/configs?dataId=com.iseed-edu&group=ktjx&tenant=7ac2eb679d1cde09f5ab172134eced7b HTTP/1.1
Host: 192.168.15.44:10211
Client-Version: Nacos-CSharp-Client-v0.2.7
User-Agent: Nacos-CSharp-Client-v0.2.7
RequestId: 64c2a0e0-86c3-4d3b-8fda-04553b518ae4
Request-Module: Naming
accessToken: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNTk1MDczNjI2fQ.YFuex4P_eSiDCn9GyQRO6_O4e6lo_vOa4XCiJNNC4bU

HTTP/1.1 403
Content-Type: application/json;charset=UTF-8
Date: Sat, 18 Jul 2020 07:13:57 GMT
afterTime: 2020-07-18 15:13:57 520215
Content-Length: 133

{"timestamp":"2020-07-18T07:13:57.645+0000","status":403,"error":"Forbidden","message":"unknown user!","path":"/nacos/v1/cs/configs"}

这个请求querystring 带 accessToken
GET http://192.168.15.44:10211/nacos/v1/cs/configs?dataId=com.iseed-edu&group=ktjx&tenant=7ac2eb679d1cde09f5ab172134eced7b&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNTk1MDczNjI2fQ.YFuex4P_eSiDCn9GyQRO6_O4e6lo_vOa4XCiJNNC4bU HTTP/1.1
Host: 192.168.15.44:10211
Client-Version: Nacos-CSharp-Client-v0.2.7
User-Agent: Nacos-CSharp-Client-v0.2.7
RequestId: 64c2a0e0-86c3-4d3b-8fda-04553b518ae4
Request-Module: Naming
accessToken: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNTk1MDczNjI2fQ.YFuex4P_eSiDCn9GyQRO6_O4e6lo_vOa4XCiJNNC4bU

HTTP/1.1 200
Config-Type: text
Content-MD5: cdf14bdc318ae96d689e011b0bdcb537
Pragma: no-cache
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache,no-store
Last-Modified: Sat, 18 Jul 2020 07:13:10 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 338
Date: Sat, 18 Jul 2020 07:17:00 GMT
afterTime: 2020-07-18 15:17:00 784563

{
"ConnectionStrings":{
"Default":"Server=127.0.0.1;Port=3306;Database=demo;User Id=root;Password=123456;"
},
"version":"测试version",
"AppSettings":{
"Str":"val",
"num":1,
"arr":[
1,
2,
3,
4,
5,
6,
77
],
"subobj":{
"a":"b"
}
}
}

**Comment by catcherwong** [comment]
from catcherwong/nacos-sdk-csharp#32 @catcherwong 

------

@wangengzheng  谢谢您对这个项目感兴趣！

重新看了一下代码，发现确实是放在QueryString里面的。

java sdk

https://github.com/alibaba/nacos/blob/cda3f142306a4bfb2cf377ad3883b27ee91d005b/client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java#L138-L141

go sdk

https://github.com/nacos-group/nacos-sdk-go/blob/3a6d4ff418be6d9cab4178a63013fa0ff0b50551/common/nacos_server/nacos_server.go#L63-L93

**injectSecurityInfo** 这个方法就是把accessToken放上去。

这边我没注意到这个，想当然就放到请求头了。

https://github.com/nacos-group/nacos-sdk-csharp/blob/892a5e792a3cca50281dd1ea24af98306cacd467/src/Nacos/Config/Http/ServerHttpAgent.cs#L101-L112

**Comment by wangengzheng** [comment]
if (!paramValues.ContainsKey(ConstValue.ACCESS_TOKEN))
                {
                    paramValues.Add(ConstValue.ACCESS_TOKEN, _securityProxy.GetAccessToken());
                }

**Comment by catcherwong** [comment]
can you send a PR to fixed this issue? 😄
