### ISSUE TITLE
当我使用appsettings.json中urls参数时遇到sdk无法正确自动识别地址的问题，请问该如何解决？

### ISSUE THREAD

**Issue by fengbozs** [nacos-group/nacos-sdk-csharp#106]
![image](https://user-images.githubusercontent.com/24955501/119109573-ddbaf080-ba53-11eb-9116-3309111611e8.png)
 
而且当我直接运行程序而不是在vs中调试时，直接显示使用了80端口，但我程序监听的是6001端口：
![image](https://user-images.githubusercontent.com/24955501/119109852-207cc880-ba54-11eb-944a-c7085068da51.png)

**Comment by catcherwong** [comment]
@fengbozs  谢谢您对这个项目感兴趣。

目前并不会读取 appsettings.json中urls参数 作为服务地址。

获取服务地址的优先级顺序如下：

1. 自己配置的IP和端口，非urls
2. program 里面的 `UseUrls("http://*:8787")`
3. `ASPNETCORE_URLS` 这个环境变量
4. 命令行启动的 `--urls=xxxx`
5. 获取到的当前机器的ip和端口(80或指定的)

同时建议：

1. docker 环境下，推荐用 ASPNETCORE_URLS 这个环境变量来处理。
2. 非docker环境下，在启动命令里面指定， dotnet xx.dll --urls=xxxx
