### ISSUE TITLE
关于V2版服务发现的服务列表更新问题

### ISSUE THREAD

**Issue by renzhenWrok** [nacos-group/nacos-sdk-csharp#109]
项目在使用1.0.3版本的sdk时发现，UpdateTask内的Timer在执行服务列表刷新时，会引发异常，如下：
System.ArgumentOutOfRangeException:“Number must be either non-negative and less than or equal to Int32.MaxValue or -1. Arg_ParamName_Name”

阅读master的源码发现该问题已修复。不知作者何时会发布新的版本来更新这个问题？

**Comment by catcherwong** [comment]
这周末或下周一会发布正式版，现在预览版已经修复这个问题的了。
