### ISSUE TITLE
Can INacosServerManager add some other methods to adapt more requirements

### ISSUE THREAD

**Issue by qiuhaohui163** [nacos-group/nacos-sdk-csharp#11]
```cs
var res = await _nacosServerManager.GetServerAsync("test1");
```
返回地址为空;
看源码NacosServerManager实现
```cs
var serviceInstances = await _client.ListInstancesAsync(new ListInstancesRequest
                {
                    ServiceName = serviceName,                
                    HealthyOnly = true,
                });
```
此处new ListInstancesRequest时 只有serviceName, 故如果自定义cluster, namespace 或者 group, 则nacos/v1/ns/instance/list接口 返回空
是否可增加以上参数的方法重载

**Comment by catcherwong** [comment]
@qiuhaohui163 谢谢您对这个项目感兴趣！

这个是可以添加重载的，目前`NacosServerManager`只支持了最简单的使用方法。

如果您方便的话，也可以提个PR来帮我们完善这一块。

-------

Thanks for your interest in this project.

Yes, we can add other methods to adapt your issue. `NacosServerManager` only support the simplest usages.

If it is convenient for you, you can also submit a PR to help us improve this one.

**Comment by catcherwong** [comment]
release 0.3.0-alpha20200730001427

https://github.com/nacos-group/nacos-sdk-csharp/blob/9b84f7ac0a632d3f721bb7591269806b47e7430e/src/Nacos.AspNetCore/INacosServerManager.cs#L5-L14
