### ISSUE TITLE
使用AddNacosV2Configuration报错是什么问题

### ISSUE THREAD

**Issue by lovexian** [nacos-group/nacos-sdk-csharp#113]
我按照readme配置为builder.AddNacosV2Configuration(c.GetSection("NacosConfig")); 会报如下错误: 
Nacos.V2.Config.NacosConfigService[0]
      async listen config change error
Nacos.V2.Exceptions.NacosException: Client not connected,current status: 2 
使用builder.AddNacosConfiguration(c.GetSection("NacosConfig"));可以正常.而且不管是哪个都是要在ConfigureServices中添加services.AddNacos(Configuration);才行,请问是两者有何区别? 而且我按readme配置服务注册也同样会报找不到客户端的错误

**Comment by catcherwong** [comment]
参考 #108

Client not connected，基本就是和服务端连接的问题。

**Comment by lovexian** [comment]
报错确实是服务端版本问题,现在运行也没问题了,但是服务列表并没有数据,这是怎么回事?
ConfigureServices也加了:
            services.AddNacosAspNet(Configuration);
            services.AddNacos(Configuration);
            services.AddHostedService<ListenConfigurationBgTask>();

**Comment by catcherwong** [comment]
不附上具体的信息，完全猜不出来 的。

**Comment by lovexian** [comment]
监听配置如下:
"nacos": {
    "ServerAddresses": [ "http://xxxxx.cn:8848" ], //nacos平台地址
    "DefaultTimeOut": 15000, //默认超时时间
    "Namespace": "3c1ce95b-3604-4911-b722-84ce9b12cc8f", //目标组别ID
    "ListenInterval": 1000, //监听间隔
    "ServiceName": "xxxxx.Api", //服务名称
    "Weight": 10, //权重
    "Port": 8013, //当前服务端口
    "Ip": "192.168.0.190" //当前服务ip
  }

运行信息:
info: Nacos.V2.Naming.NacosNamingService[0]
      Grpc re-connect, redo subscribe services
info: Nacos.V2.Naming.NacosNamingService[0]
      Grpc re-connect, redo register services
info: Nacos.AspNetCore.V2.RegSvcBgTask[0]
      register instance to nacos server, 【Instance{instanceId='', ip='192.168.0.190', port=8013, weight=10, healthy=True, enabled=True, ephemeral=True, clusterName='DEFAULT', serviceName='IOMP.IEMSGX.Api', metadata={"preserved.register.source":"ASPNET_CORE","DOTNET_VERSION":"3.1.13","HOST_OS":"Microsoft Windows NT 6.2.9200.0"}}】
info: Nacos.V2.Naming.NacosNamingService[0]
      [REGISTER-SERVICE] 3c1ce95b-3604-4911-b722-84ce9b12cc8f registering service IOMP.IEMSGX.Api with instance Instance{instanceId='', ip='192.168.0.190', port=8013, weight=10, healthy=True, enabled=True, ephemeral=True, clusterName='DEFAULT', serviceName='IOMP.IEMSGX.Api', metadata={"preserved.register.source":"ASPNET_CORE","DOTNET_VERSION":"3.1.13","HOST_OS":"Microsoft Windows NT 6.2.9200.0"}}
info: System.Net.Http.HttpClient.NacosClient.LogicalHandler[100]
      Start processing HTTP request POST http://cloud.ilng.cn:8848/nacos/v1/cs/configs/listener
info: System.Net.Http.HttpClient.NacosClient.ClientHandler[100]
      Sending HTTP request POST http://cloud.ilng.cn:8848/nacos/v1/cs/configs/listener
info: System.Net.Http.HttpClient.NacosClient.LogicalHandler[100]
      Start processing HTTP request POST http://cloud.ilng.cn:8848/nacos/v1/cs/configs/listener
info: System.Net.Http.HttpClient.NacosClient.ClientHandler[100]
      Sending HTTP request POST http://cloud.ilng.cn:8848/nacos/v1/cs/configs/listener
info: System.Net.Http.HttpClient.NacosClient.LogicalHandler[100]
      Start processing HTTP request POST http://cloud.ilng.cn:8848/nacos/v1/cs/configs/listener
info: System.Net.Http.HttpClient.NacosClient.ClientHandler[100]
      Sending HTTP request POST http://cloud.ilng.cn:8848/nacos/v1/cs/configs/listener
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:8013
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\工作\git\new\iomp.iemsgx\IOMP.IEMS.Api
 System.Net.Http.HttpClient.NacosClient.ClientHandler[101]
      Received HTTP response after 29600.8399ms - OK
info: System.Net.Http.HttpClient.NacosClient.LogicalHandler[101]
      End processing HTTP request after 29612.0118ms - OK
info: System.Net.Http.HttpClient.NacosClient.LogicalHandler[100]
      Start processing HTTP request POST http://cloud.ilng.cn:8848/nacos/v1/cs/configs/listener
info: System.Net.Http.HttpClient.NacosClient.ClientHandler[100]
      Sending HTTP request POST http://cloud.ilng.cn:8848/nacos/v1/cs/configs/listener
info: System.Net.Http.HttpClient.NacosClient.ClientHandler[101]
      Received HTTP response after 29555.5914ms - OK
info: System.Net.Http.HttpClient.NacosClient.LogicalHandler[101]
      End processing HTTP request after 29590.2007ms - OK

监听是正常,就是没有注册服务

**Comment by catcherwong** [comment]
你服务端到底是什么版本？

`services.AddNacosAspNet(Configuration);` 这个默认走的是 grpc

`services.AddNacos(Configuration);` 这个默认走的是 http

看你注册服务走的是 v2， 配置又是 v1

**Comment by lovexian** [comment]
服务端是2.0.1的版本,我把配置改成readme示例里的v2配置也是注册不上,
"nacos": {
    "EndPoint": "",
    "ServerAddresses": [ "http://cloud.ilng.cn:8848" ],
    "DefaultTimeOut": 15000,
    "Namespace": "cs",
    "ListenInterval": 1000,
    "ServiceName": "IOMP.IEMSGX.Api",
    "GroupName": "DEFAULT_GROUP",
    "ClusterName": "DEFAULT",
    "Ip": "192.168.0.190",
    "PreferredNetworks": "", // select an IP that matches the prefix as the service registration IP
    "Port": 8013,
    "Weight": 10,
    "RegisterEnabled": true,
    "InstanceEnabled": true,
    "Ephemeral": true,
    "Secure": false,
    "AccessKey": "",
    "SecretKey": "",
    "UserName": "nacos",
    "Password": "nacos",
    "ConfigUseRpc": true,
    "NamingUseRpc": true,
    "NamingLoadCacheAtStart": "",
    "LBStrategy": "WeightRandom" //WeightRandom WeightRoundRobin
    //"Metadata": {
    //  "aa": "bb",
    //  "cc": "dd"
    //}
  }

**Comment by catcherwong** [comment]
补充一下日志和控制台信息，不行就弄一个能重现的代码。

**Comment by lovexian** [comment]
info: Nacos.V2.Naming.NacosNamingService[0]
      Grpc re-connect, redo subscribe services
info: Nacos.V2.Naming.NacosNamingService[0]
      Grpc re-connect, redo register services
info: Nacos.AspNetCore.V2.RegSvcBgTask[0]
      register instance to nacos server, 【Instance{instanceId='', ip='192.168.0.190', port=8013, weight=10, healthy=True, enabled=True, ephemeral=True, clusterName='DEFAULT', serviceName='IOMP.IEMSGX.Api', metadata={"preserved.register.source":"ASPNET_CORE","DOTNET_VERSION":"3.1.13","HOST_OS":"Microsoft Windows NT 6.2.9200.0"}}】
info: Nacos.V2.Naming.NacosNamingService[0]
      [REGISTER-SERVICE] cs registering service IOMP.IEMSGX.Api with instance Instance{instanceId='', ip='192.168.0.190', port=8013, weight=10, healthy=True, enabled=True, ephemeral=True, clusterName='DEFAULT', serviceName='IOMP.IEMSGX.Api', metadata={"preserved.register.source":"ASPNET_CORE","DOTNET_VERSION":"3.1.13","HOST_OS":"Microsoft Windows NT 6.2.9200.0"}}
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:8013
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\工作\git\new\iomp.iemsgx\IOMP.IEMS.Api

**Comment by lovexian** [comment]
这是我只在ConfigureServices加了services.AddNacosAspNet(Configuration);的控制台信息.

**Comment by catcherwong** [comment]
nacos的管理界面呢？

**Comment by lovexian** [comment]
多谢解答,我又检查了下配置,是我命名空间配置错误导致的

**Comment by catcherwong** [comment]
OK，那我关了这个Issue了。
