### ISSUE TITLE
When the configuration key is repeated, Throw "key has already been added" Exception

### ISSUE THREAD

**Issue by code-jar** [nacos-group/nacos-sdk-csharp#119]
## Describe what happened (or what feature you want)

When I set up two ConfigListener,two configuration have the same keyName. An exception is thrown at startup

warn: Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider[0]
          call back reload config error
    System.ArgumentException: An item with the same key has already been added. Key: Log4netLevel
       at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
       at Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider.MsConfigListener.ReceiveConfigInfo(String configInfo)
    fail: Nacos.V2.Config.NacosConfigService[0]
          refresh content and check md5 fail ,dataid=appsettings,group=Offer,tenant=dev 
    System.ArgumentException: An item with the same key has already been added. Key: Log4netLevel
       at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
       at Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider.MsConfigListener.ReceiveConfigInfo(String configInfo)
       at Nacos.V2.Config.Impl.CacheData.SafeNotifyListener(String dataId, String group, String content, String type, String md5, String encryptedDataKey, ManagerListenerWrap wrap)
       at Nacos.V2.Config.Impl.CacheData.CheckListenerMd5()
       at Nacos.V2.Config.Impl.ConfigRpcTransportClient.RefreshContentAndCheck(CacheData cacheData, Boolean notify)

## Related code

```JSON
Group:Global
Data Id:appsettings
{
"Log4netLevel":"Warn"
}
Group:Service
Data Id:appsettings
{
"Log4netLevel":"Debug"
}
```

```csharp

var listeners = new List<ConfigListener> {
    new ConfigListener {
            DataId = "appsettings",
            Group = "Global",
            Optional = false
        },
    new ConfigListener {
            DataId = "appsettings",
            Group = "Service",
            Optional = false
        }
};

config.Listeners = listeners;
configRoot.GetSection("NacosConfig").Bind(config);
```

## Tell us your environment

- nacos-sdk-csharp version: [1.1.0]
- modular : [config]
- nacos server version: [2.0.2]
- how to host nacos server : [pc]

**Comment by code-jar** [comment]
I submitted a change, but I don't know if it will affect other places

**Comment by catcherwong** [comment]
@code-jar  Thanks for your interest in this project.

Take a look at your commit, it will not affect other places.

But there also will have some logic issues via your design.

Two `group + dataId`  contain the same JSON section will cause configuration conflict, which will cause the configuration to be overridden by the last operation.

**Comment by code-jar** [comment]
> @code-jar Thanks for your interest in this project.
> 
> Take a look at your commit, it will not affect other places.
> 
> But there also will have some logic issues via your design.
> 
> Two `group + dataId` contain the same JSON section will cause configuration conflict, which will cause the configuration to be overridden by the last operation.

Thank you, That's exactly what I need. 
I have a global configuration and an in application configuration, I want to read the global configuration when I don't have a separate configuration
