### ISSUE TITLE
为什么一直打印：Grpc Connection is disconnect, skip current redo task

### ISSUE THREAD

**Issue by moneyfengcn** [nacos-group/nacos-sdk-csharp#129]
代码跑起来后，控制台一直打印：
warn: Nacos.V2.Naming.NacosNamingService[0]
      Grpc Connection is disconnect, skip current redo task

我己经按文档说明把这两个配置为False了
        "NamingUseRpc": false,
        "ConfigUseRpc": false

**Comment by catcherwong** [comment]
这个问题已经修复了，还没发正式版。

**Comment by catcherwong** [comment]
已发布 v1.1.1 版本。
