### ISSUE TITLE
sectionName没有往下传递

### ISSUE THREAD

**Issue by hiwjcn** [nacos-group/nacos-sdk-csharp#131]
https://github.com/nacos-group/nacos-sdk-csharp/blob/475beda62e897f6c66bcf63afa41c9c595ac7313/src/Nacos.AspNetCore/V2/ServiceCollectionExtensions.cs#L22

代码质量有待提高，最好readme出一个最简配置

**Comment by catcherwong** [comment]
已经调整。会在 1.2.0 版本发布。

README，后续会不断完善。
