### ISSUE TITLE
修改配置事件的监听

### ISSUE THREAD

**Issue by aion1998** [nacos-group/nacos-sdk-csharp#133]
可以整一个修改配置事件的监听吗，nacos好像是有的
我想在修改配置后自动重新拿新配置去注册服务

**Comment by catcherwong** [comment]
参考下面这个例子。

自己定义监听，在监听里面处理相关逻辑，然后 `AddListener` 即可。


https://github.com/nacos-group/nacos-sdk-csharp/blob/1d8f54300253de133bcfdaf067a863dbf83d27e8/samples/App3/Controllers/ConfigController.cs#L62-L70

https://github.com/nacos-group/nacos-sdk-csharp/blob/1d8f54300253de133bcfdaf067a863dbf83d27e8/samples/App3/Controllers/ConfigController.cs#L49

**Comment by aion1998** [comment]
@catcherwong 

![image](https://user-images.githubusercontent.com/19725014/130020547-381c6b0e-7d36-43c0-b996-54c772496072.png)

请问一下INacosConfigService 要怎么注入，注释的方式都试过了

**Comment by catcherwong** [comment]
https://github.com/nacos-group/nacos-sdk-csharp/blob/1d8f54300253de133bcfdaf067a863dbf83d27e8/samples/App3/Startup.cs#L36-L49

**Comment by aion1998** [comment]
感谢😋😋😋😋

**Comment by aion1998** [comment]
![image](https://user-images.githubusercontent.com/19725014/130192756-b73e62a6-c544-41b0-8c39-acd51b4dc250.png)

@catcherwong ....请问一下，要怎么重新注册服务，我给整不会了，麻烦前辈可以指点一二或者有没有相关需求demo

**Comment by catcherwong** [comment]
你这个需求，改服务的配置，理论上变更的只是服务的元数据，权重这些内容吧？

如果是这种情况，你需要在监听配置里面实现下面几个东西：

1. 根据**服务名**和辅助信息，查询一次明细信息，找到当前这个Instance的IP和端口
2. 调用 **DeregisterInstance** 方法，注销当前实例
3. 根据监听拿到的新数据，结合服务名，IP，端口等信息，调用 **RegisterInstance** 方法进行注册实例。

> PS： 第一个主要是获取当前实例的IP和端口，如果可以通过其他方式获取到，也可以不用去查询一次。

如果涉及到变更服务名，IP，和端口这几个核心内容，建议就没必要进行监听来处理这样的操作了，重启服务比做这些操作更简单。
