### ISSUE TITLE
关于k8s环境下的公开端口 和nacos客户端不能正常连接问题

### ISSUE THREAD

**Issue by worldofchu** [nacos-group/nacos-sdk-csharp#143]
1、k8s部署nacos成功
2、公开端口 8848 到80端口，并域名 nacosxx.com，但是k8s内部service还有 9848 和9849 端口未做处理
3、浏览器打开http://nacosxx.com/nacos成功！！（配置了hosts）
4、aspnetcore程序 配置 ServerAddresses  为 http://nacosxx.com/  
5、测试报错，
Nacos.V2.Config.NacosConfigService[0]
      async listen config change error
      Nacos.V2.Exceptions.NacosException: Client not connected,current status: STARTING
         at Nacos.V2.Remote.RpcClient.Request(CommonRequest request, Int64 timeoutMills) in Nacos.dll:token 0x600042d+0x2db
         at Nacos.V2.Config.Impl.ConfigRpcTransportClient.RequestProxy(RpcClient rpcClientInner, CommonRequest request) in Nacos.dll:token 0x6000776+0xa9

6、fiddler抓包看到有2个 http请求  域名为 nacosxx.com  
POST http://nacosxx.com/nacos/v1/auth/users/login HTTP/1.1
Host: nacosxx.com
Content-Type: application/x-www-form-urlencoded
Content-Length: 35

username=nacos&password=nacosw11

这俩都返回200

**Comment by worldofchu** [comment]
无语！！！！！！
aspnetcore程序 配置 ServerAddresses 为 http://nacosxx.com/
修正为
  http://nacosxx.com:80/  
问题解决！！！！！
这应该算是SDK的一个bug把？？？

**Comment by catcherwong** [comment]
用的nacos server版本是多少？sdk 版本是多少？

> Nacos.V2.Exceptions.NacosException: Client not connected,current status: STARTING

出现这个错误，说明客户端与服务端建立 grpc 连接时有问题。

如果 nacos server 是 2.x 的，请检查 grpc 的端口有没有开放，参考  https://nacos.io/zh-cn/docs/2.0.0-compatibility.html

如果 nacos server 是 1.x 的，请把客户端的 rpc 的配置设置为 false.


> 6、fiddler抓包看到有2个 http请求 域名为 nacosxx.com

这个是你配置了用户名和密码，导致会去请求这个接口拿 token。请求token这个是 HTTP的。
