### ISSUE TITLE
服务注册发现问题

### ISSUE THREAD

**Issue by SwingZhang** [nacos-group/nacos-sdk-csharp#147]
使用sdk服务注册的时候，如何动态的从程序中获取ip和端口作为服务注册的端口，如程序启动时加入了--urls="http://*:8080"

**Comment by catcherwong** [comment]
如果用的是 `nacos-sdk-csharp.AspNetCore` 这个包，它会自动识别应用的ip和端口。

识别的优先级如下：

1. 在配置文件指定了IP和端口
2. IServerAddressesFeature
3. 环境变量 ASPNETCORE_URLS
4. 命令行参数 --urls
5. 当前服务器IP+指定端口

详见：https://github.com/nacos-group/nacos-sdk-csharp/blob/dev/src/Nacos.AspNetCore/UriTool.cs#L14

**Comment by SwingZhang** [comment]
非常感谢你的回复，这个优先级在微服务下是否可以调整，我设置urls参数，但是看最终生成效果应该是获取了IServerAddressesFeature里面的ip和端口









------------------ 原始邮件 ------------------
发件人:                                                                                                                        "nacos-group/nacos-sdk-csharp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月13日(星期一) 下午5:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nacos-group/nacos-sdk-csharp] 服务注册发现问题 (#147)





 
如果用的是 nacos-sdk-csharp.AspNetCore 这个包，它会自动识别应用的ip和端口。
 
识别的优先级如下：
  
在配置文件指定了IP和端口
 
IServerAddressesFeature
 
环境变量 ASPNETCORE_URLS
 
命令行参数 --urls
 
当前服务器IP+指定端口
  
详见：https://github.com/nacos-group/nacos-sdk-csharp/blob/dev/src/Nacos.AspNetCore/UriTool.cs#L14
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by catcherwong** [comment]
按理说，IServerAddressesFeature，拿到的 IP + Port 应该是比较准确。是这个拿到的和你用urls参数指定的不一样？

**Comment by SwingZhang** [comment]
是的不一样------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月13日(星期一) 晚上6:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nacos-group/nacos-sdk-csharp] 服务注册发现问题 (#147)

**Comment by catcherwong** [comment]
![image](https://user-images.githubusercontent.com/8394988/133232772-7a7181dd-c510-449c-a7df-8f82129b4f2b.png)

这边试了一下，是正常的，需要你那边看一下是不是有其他配置导致获取不到期望值了。

**Comment by SwingZhang** [comment]
好的，非常感谢，我这边再看看是不是哪里的配置影响了，nacos的配置是不是就是开源项目的里面的配置就行，IP="",Port=0?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nacos-group/nacos-sdk-csharp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 下午5:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nacos-group/nacos-sdk-csharp] 服务注册发现问题 (#147)





 

 
这边试了一下，是正常的，需要你那边看一下是不是有其他配置导致获取不到期望值了。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by catcherwong** [comment]
如果你想直接指定的话，就是这两个配置。

**Comment by SwingZhang** [comment]
大佬在咨询一个问题，docker集群部署模式下，如何在容器启动的时候动态设置这个ip和端口？
一直没有找到解决方案，如果你知道麻烦指点下，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nacos-group/nacos-sdk-csharp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 晚上8:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nacos-group/nacos-sdk-csharp] 服务注册发现问题 (#147)





 
如果你想直接指定的话，就是这两个配置。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by catcherwong** [comment]
如果只是在服务器上直接起多个容器的情况的话，可以在启动脚本中，获取到当前服务器的IP，以及你要启动的端口，指定环境变量就好 。

**Comment by SwingZhang** [comment]
大佬，咨询一下，docker部署的时候如何在docker run的之后指定urls参数啊，或者说docker部署的情况下，如何通过命令动态配置nacos注册的ip+端口




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nacos-group/nacos-sdk-csharp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 下午5:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nacos-group/nacos-sdk-csharp] 服务注册发现问题 (#147)





 

 
这边试了一下，是正常的，需要你那边看一下是不是有其他配置导致获取不到期望值了。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by catcherwong** [comment]
docker run 建议就是 用 ASPNETCORE_URLS 这个环境变量来指定。

```sh
docker run -d -p $port:80 \
                -e ASPNETCORE_ENVIRONMENT=$e \
                -e ASPNETCORE_URLS=http://$ip:$port \
                -e TZ=Asia/Shanghai \
                -e DOTNET_RUNNING_IN_CONTAINER=true \             
                --name $proj-$e-$port \
                --restart=always  \           
                xxxx
```
