### ISSUE TITLE
日志提示服务注册成功,但是在ui控制台看不到相应的服务

### ISSUE THREAD

**Issue by liuhll** [nacos-group/nacos-sdk-csharp#154]
当我使用`NacosNamingService`注册一个服务实例时,日志提示我服务已经注册成功,但是在nacos管理端却看不到相应的服务.

示例代码
```csharp
        protected override async Task RegisterServerToServiceCenter(ServerDescriptor serverDescriptor)
        {
            foreach (var endpoint in serverDescriptor.Endpoints)
            {
                var instance = new Instance()
                {
                    InstanceId = endpoint.ToString(),
                    ServiceName = serverDescriptor.HostName,
                    Ephemeral = true,
                    Enabled = true,
                    Ip = endpoint.Host,
                    Port = endpoint.Port,
                    Metadata = new Dictionary<string, string>()
                    {
                        { "ServiceProtocol", endpoint.ServiceProtocol.ToString() },
                        { "TimeStamp", serverDescriptor.TimeStamp.ToString() },
                        { "ProcessorTime", endpoint.ProcessorTime.ToString() }
                    },
                };
                await _nacosNamingService.RegisterInstance(serverDescriptor.HostName, instance);
            }
        }
```
日志:
![image](https://user-images.githubusercontent.com/16488441/134442582-eee52785-130c-48ae-b950-379094f412c6.png)

UI管理端却看不到相应的服务列表:
![image](https://user-images.githubusercontent.com/16488441/134442648-d4275789-9bf6-4476-bd93-d03428cfa9f4.png)

**Comment by liuhll** [comment]
我发现必须在要注册在public名称空间下,在控制台才会显示服务列表,SDK提供的API貌似没有找到如何创建名称空间

**Comment by catcherwong** [comment]
从你的日志来看，是注册到了  **silky** 这个命名空间下面了。

![image](https://user-images.githubusercontent.com/8394988/134485008-93a0bfc7-8e17-46b9-9c50-2429f090d287.png)


你的控制台上面，并没有创建 **silky** 这个命名空间，创建之后，就会在下面看到的了

**Comment by catcherwong** [comment]
目前 SDK 没有提供命名空间相关的内容，nacos 也未公开对应的方法。

**Comment by liuhll** [comment]
![image](https://user-images.githubusercontent.com/16488441/134602259-25884ba4-7191-4de9-864f-63b9f6cc00b3.png)
nacos是同样的配置,配置在控制台上却看不到数据,服务列表现在有数据了(都是在public名称空间下)

![image](https://user-images.githubusercontent.com/16488441/134602344-65a961bd-2a37-4e78-84ae-fbf1ebb7ed54.png)
![image](https://user-images.githubusercontent.com/16488441/134602378-5d54201a-abb4-4057-b0a3-2ab00be3a3a7.png)

**Comment by liuhll** [comment]
还有我发现nacos的配置`namingUseRpc: false`的情况下,是订阅不到`IEventListener`时间的,是本来不支持,还是sdk的bug？

**Comment by catcherwong** [comment]
public 命名空间，正确的方式应当是留空。对应下图的命名空间ID

![1632495743(1)](https://user-images.githubusercontent.com/8394988/134697125-fa5ef628-8c08-4510-b6e6-ab64d87bb0a2.png)

如果方便的话，把配置贴出来，才知道你配置的是否有问题，不然就是再猜问题在那里。

**Comment by catcherwong** [comment]
> 还有我发现nacos的配置namingUseRpc: false的情况下,是订阅不到IEventListener事件的,是本来不支持,还是sdk的bug？

false的情况下，服务端是通过udp的方式返回更新结果的，是有具体的错误原因还是其他什么表现？

**Comment by liuhll** [comment]
我nacos的配置如下:
```yaml
registrycenter:
  type: Nacos
  namespace: public
  serverAddresses:
    - http://127.0.0.1:8848/
    - http://127.0.0.1:8849/
    - http://127.0.0.1:8850/
  userName: nacos
  password: nacos
  groupName: DEFAULT_GROUP
  clusterName: DEFAULT
  registerEnabled: true
  instanceEnabled: true
  namingUseRpc: true  #如果为false，则订阅不到IEventListener事件
```

发布配置的代码如下:
```csharp
  public async Task PublishServices(string hostName, ServiceDescriptor[] serviceDescriptors,
            long timeoutMs = 5000)
 {
            if (m_services.TryGetValue(hostName, out var cacheServiceDescriptors))
            {
                if (serviceDescriptors.All(p => cacheServiceDescriptors.Any(q => p == q)))
                {
                    return;
                }
            }

            var serviceConfigValue = _serializer.Serialize(serviceDescriptors);
            var result = await _nacosConfigService.PublishConfig(hostName, _nacosRegistryCenterOptions.GroupName,
                serviceConfigValue);

 }
```

日志输出:
```
[2021/09/26 09:02:06 Information] [config_rpc_client] [publish-single] ok, dataId=AnotherHostDemo, group=DEFAULT_GROUP, tenant=public, config=[{"id":"api.wstest","application":"AnotherHostDemo","serviceName":"WsTestAppService
","serviceProtoco... 

```
从日志的输出看是配置信息是写成功的,而且我也能够正常的读取到配置信息,但是就是在控制台看不到配置的数据

![image](https://user-images.githubusercontent.com/16488441/134789737-94385fe6-5c64-4138-8867-8aea4746f6d8.png)

**Comment by liuhll** [comment]
> > 还有我发现nacos的配置namingUseRpc: false的情况下,是订阅不到IEventListener事件的,是本来不支持,还是sdk的bug？
> 
> false的情况下，服务端是通过udp的方式返回更新结果的，是有具体的错误原因还是其他什么表现？

false的情况下，在服务运行后我能在控制台的订阅者列表中看到服务的相关的订阅信息,但是过一会儿订阅者信息就不不在了

**Comment by catcherwong** [comment]
> 从日志的输出看是配置信息是写成功的,而且我也能够正常的读取到配置信息,但是就是在控制台看不到配置的数据

配置的问题已经在前面回复你了，先了解一下nacos的命名空间。

问题这里 ` namespace: public`

https://github.com/nacos-group/nacos-sdk-csharp/issues/154#issuecomment-926699445

**Comment by catcherwong** [comment]
> false的情况下，在服务运行后我能在控制台的订阅者列表中看到服务的相关的订阅信息,但是过一会儿订阅者信息就不不在了

这个我晚点试一下。

另外，你都已经用的 nacos 2.x 了，为什么要考虑把这个设置成false呢？这个不是最好的组合呀。

**Comment by liuhll** [comment]
我想每种场景都试一下
