### ISSUE TITLE
服务发现疑问

### ISSUE THREAD

**Issue by thicktao** [nacos-group/nacos-sdk-csharp#155]
1、有服务app1和app2。当app1节点全部宕机时，app2这边收到grpc推送后，发现app1对应host为空，此时并不会将本地缓存的app1服务标记为healthy=false,这样造成客户端不太好判断该app1节点是否还处于健康中，客户端直接使用会导致异常发生，不知道这样的姿势对不对?
2、如果在容器里面，ip是随机的，这块怎么注册呢？

**Comment by catcherwong** [comment]
> 当app1节点全部宕机时，app2这边收到grpc推送后，发现app1对应host为空

1. app1节点全部宕机，这个时候 app1 与 nacos server 的grpc长连接都已经断开了，这个时候去查询实例列表返回的应该是空。

2. 按你这个描述，app2，应该是 `Subscribe` 了 app1 ，这个时候会有一个更新的任务会主动去查询最新的服务列表，缓存是会自动更新的。

你去查服务列表，是通过那个方法去查的？不同的方法和参数，行为会有一点出入。


> 如果在容器里面，ip是随机的，这块怎么注册呢？

启动脚本中，加入获取本机IP和预设端口的方法，传递到 ASPNETCORE_URLS 这个环境变量里面。

如果你知道确切的网段信息，也可以在配置文件中设置**preferredNetworks**。

**Comment by catcherwong** [comment]
可以参考 #147

**Comment by thicktao** [comment]
1、是的，app2订阅了app1的变更通知，当app2需要调用app1服务，而app1全部宕机时，采用SelectOneHealthyInstance方法，能够查询到app1，healthy=true。我看了一下代码，IsEmptyOrErrorPush判断hosts不存在任何节点时，就会返回，不回去更新本地缓存
![image](https://user-images.githubusercontent.com/40555417/134831533-dfcf43d8-cd7f-4734-9903-b95447cdf2e4.png)
2、容器ip那个我知道了，我去试试哈

**Comment by catcherwong** [comment]
全部宕机这种情况，我要看一下这种情况怎么处理好一点。

**Comment by thicktao** [comment]
@catcherwong 好的，感谢！

**Comment by catcherwong** [comment]
具体的行为和配置可以看看下面两个单元测试。

https://github.com/nacos-group/nacos-sdk-csharp/blob/745f2b5acdee9ba73dfcedb007960010eed4642b/tests/Nacos.Tests/Naming/Cache/ServiceInfoHolderTests.cs#L61-L104
