### ISSUE TITLE
nacos-sdk-csharp.YamlParser没有发布最新版，不支持nacos-sdk-csharp 1.2.1

### ISSUE THREAD

**Issue by DillonHuang** [nacos-group/nacos-sdk-csharp#160]
## Describe what happened (or what feature you want)

使用nacos-sdk-csharp 1.2.1，用YamlParser编译失败
```
 builder.AddNacosV2Configuration(section, Nacos.YamlParser.YamlConfigurationStringParser.Instance);
```

我看了下`YamlConfigurationStringParser`源码已经改了，就是没有打包发布到nuget上

可以考虑下`YamlConfigurationStringParser`和`nacos-sdk-csharp`使用统一版本号

**Comment by catcherwong** [comment]
收到，这个是上次调整 github action 的脚本时，忘记把 parser 的包加上去了。

他们的版本是一致的。这边晚点发个包。
