### ISSUE TITLE
配置文件中 使用 命名空间绑定配置时不起作用  使用 ID绑定可用

### ISSUE THREAD

**Issue by 914268308** [nacos-group/nacos-sdk-csharp#165]
![image](https://user-images.githubusercontent.com/15066346/142115562-d066a150-3a9e-42cc-8c26-252dcf782278.png)

使用"Namespace": "Nacos_dev", 时无法读取Nacos配置文件  
改用     "Tenant": "51e34ef3-87bd-4b3d-821c-b7ee1c595e5e", 时可以 
![image](https://user-images.githubusercontent.com/15066346/142116797-947b9648-2e61-4acd-ad3a-60bae7a4b937.png)

**Comment by catcherwong** [comment]
两个都是填Id的，不是填名称的。

**Comment by 914268308** [comment]
那这个本身就是错误的设计了

**Comment by myokok** [comment]
为啥我填了Id 还是读取不了配置文件？目前只能读取public命名空间下的配置文件。

**Comment by 914268308** [comment]
我修改了源码之后可以用了

**Comment by 914268308** [comment]
2.0.3用的grpc实现的，需要传tenant才能使用，建议把命名空间和tenant设置成一样的，就可以了
