### ISSUE TITLE
订阅多个节点包含一个text类型的配置无法解析

### ISSUE THREAD

**Issue by knowyi** [nacos-group/nacos-sdk-csharp#166]
你好，我有个问题
nacos版本1.3.2 以前使用的sdk版本0.8.0，目前升级到最新版本订阅多个节点，如果有一个配置是text类型无法进行解析，但是以前的版本是支持的，请问能否兼容一下查看了一下0.8.0的源码以前有一个异常判断
![image](https://user-images.githubusercontent.com/7392434/142602418-6dc26a1a-26f7-411f-ba3c-152a351b38eb.png)

**Comment by catcherwong** [comment]
看了一下0.8.0版本的代码，似乎没有看到这一段代码 

https://github.com/nacos-group/nacos-sdk-csharp/blob/v0.8.0/src/Nacos.Microsoft.Extensions.Configuration/NacosConfigurationProvider.cs#L130-L135

**Comment by catcherwong** [comment]
截图的这个，应该是解析失败后，直接把这个解析失败的 `dataid` 作为配置根节点的一部分了，这样其实不是特别好。

试想一下，用的是json解析器，dataid-1 的内容是 `{"a":"b"}` dataid-2 的内容是 `123(不能parser成功的一个值)`，同时监听两个，意味着最终的结果会是

```JSON
{
   "a":"b",
  "dataid-2":"123(不能parser成功的一个值)"
}
```

用 `_configuration["a"] ` 可以取出 b

但是想取出 `123(不能parser成功的一个值)`， 要用  `_configuration["dataid-2"] ` 。

**Comment by knowyi** [comment]
> 截图的这个，应该是解析失败后，直接把这个解析失败的 `dataid` 作为配置根节点的一部分了，这样其实不是特别好。
> 
> 试想一下，用的是json解析器，dataid-1 的内容是 `{"a":"b"}` dataid-2 的内容是 `123(不能parser成功的一个值)`，同时监听两个，意味着最终的结果会是
> 
> ```json
> {
>    "a":"b",
>   "dataid-2":"123(不能parser成功的一个值)"
> }
> ```
> 
> 用 `_configuration["a"] ` 可以取出 b
> 
> 但是想取出 `123(不能parser成功的一个值)`， 要用 `_configuration["dataid-2"] ` 。
> 
> 这个有一定的约定性，需要放开讨论一下，看一下有多少人有类似这种需求。

可能是公司其他人下载的0.8.0的代码 添加的那段代码。我认为nacos支持text格式的情况下，可能兼容一下会更好。
目前我如果需要兼容的话 是不是还需要再你源码版本是自己去做一下？还是有别的办法能够支持

**Comment by catcherwong** [comment]
如果是想集成.NET Core的配置体系，目前的最佳做法应该是，把配置值改成可以解析的。

就现阶段来看，配置的类型(text,json,yaml.ini)其实并不重要，主要是配置的值能不能被 parser 解析出来。

如果可以不集成，那么可以直接用 SDK 提供的 `INacosConfigService.GetConfig`  方法获取即可。

**Comment by knowyi** [comment]
> 如果是想集成.NET Core的配置体系，目前的最佳做法应该是，把配置值改成可以解析的。
> 
> 就现阶段来看，配置的类型(text,json,yaml.ini)其实并不重要，主要是配置的值能不能被 parser 解析出来。
> 
> 如果可以不集成，那么可以直接用 SDK 提供的 `INacosConfigService.GetConfig` 方法获取即可。

好的，我还有一个问题 我订阅的两个dataid 有相同的节点 配置被覆盖了，这个可以自己来决定是否覆盖吗？
