### ISSUE TITLE
新建命名空间，配置文件读取不了

### ISSUE THREAD

**Issue by myokok** [nacos-group/nacos-sdk-csharp#168]
在使用nacos-sdk-csharp.Extensions.Configuration组件，Program里的代码，如何打印日志出来啊？ 现在出现错误，都没有啥有用的信息，很难排查问题。
```
          .ConfigureAppConfiguration((context, builder) =>
            {
                string env = getENV(args);
                var c = builder.AddJsonFile(path: $"appsettings.{env}.json", optional: true, reloadOnChange: true).Build();

                var test = c.GetSection("NacosConfig").GetValue<string>("Namespace");
                builder.AddNacosV2Configuration(c.GetSection("NacosConfig"));
            })
```

**Comment by 914268308** [comment]
把命名空间和tenant设置成一样的值，再试一下

**Comment by catcherwong** [comment]
想看日志的话，参考这个例子，把 Log 传进去。

https://github.com/nacos-group/nacos-sdk-csharp/blob/db474a5fe9e63e9c88272aee9dda842425b21c62/samples/MsConfigApp/Program.cs#L30

**Comment by catcherwong** [comment]
新版本请使用 Namespace， Tenant即将废弃。

https://github.com/nacos-group/nacos-sdk-csharp/blob/db474a5fe9e63e9c88272aee9dda842425b21c62/src/Nacos.Microsoft.Extensions.Configuration/NacosV2ConfigurationSource.cs#L17-L21

**Comment by myokok** [comment]
我找到原因了，Listeners里多加了一个节点，导致所有数据都出不来。这个是不是有点不合理？关键是没有正确的错误提示。

**Comment by catcherwong** [comment]
Listeners 里面的每个节点都有一个 **Optional** 的配置，这个配置决定了当前的dataid是必须的还是可选的。

你填的是 false，节点又不在，必然是报错的。

**Comment by myokok** [comment]
报错是正常的。如果错误提示“节点不存在”类似这样的，我就好排查了。但是现在的错误提示根据就不知道什么错误。
