### ISSUE TITLE
authentication failed of naming service

### ISSUE THREAD

**Issue by mickey2009** [nacos-group/nacos-sdk-csharp#17]
nacos开启身份认证后， 调用nacos服务注册相关的接口返回403,原因是nacos的accessToken信息需要放到querystring中，目前是放在http header里面的。
![image](https://user-images.githubusercontent.com/15685803/89302176-18a69000-d69d-11ea-9034-05c374a534ec.png)

-------

When enable auth of nacos server, calling REST APIs of naming service will return 403, due to the `accessToken` should be put in querystring, not HTTP header.

**Comment by catcherwong** [comment]
@mickey2009 谢谢您对这个项目感兴趣！

我们会尽快处理这个问题.

------

Thanks for your interest in this project.

We will take a look ASAP.

**Comment by catcherwong** [comment]
@mickey2009  Try this version `0.3.0-alpha20200805101659`  .

**Comment by catcherwong** [comment]
Closed! If you also have any question, reopen this issue or open a new one.
