### ISSUE TITLE
基于dotnet run --urls http://*:7000 --port 7000方式启动读取不到配置

### ISSUE THREAD

**Issue by ygs12** [nacos-group/nacos-sdk-csharp#170]
![image](https://user-images.githubusercontent.com/23413572/143836035-91a63cf1-7822-43c2-b029-5e614955d8cf.png)

**Comment by ygs12** [comment]
项目内的配置launchSettings.json文件
![image](https://user-images.githubusercontent.com/23413572/143836207-a8667d18-ac8c-4b09-ad5b-9a7a031bf86c.png)

**Comment by catcherwong** [comment]
看一下 #106 能不能解决你的疑问。

**Comment by ygs12** [comment]
已解决，就是有点鸡肋，解决方式如下：
1、注释掉图中指定的配置
![image](https://user-images.githubusercontent.com/23413572/144374942-c2b2f72e-6644-40c2-b3cd-9a1403b50396.png)
2、在cmd上运行的命令必须是dotnet run --urls=http://具体的IP地址:端口【特别注意：dotnet run --urls http://具体的IP地址:端口这种方式组件不认识】
![image](https://user-images.githubusercontent.com/23413572/144375559-25ae8347-de93-4cf3-b27c-9e1d9c38f3a6.png)
