### ISSUE TITLE
Windows 10 Docker环境，aps.net core + nacos 都运行在docker, 需要为gprc开放9848端口

### ISSUE THREAD

**Issue by lzymll** [nacos-group/nacos-sdk-csharp#175]
docker run -d --name=nacos -e MODE=standalone -p 8848:8848 -p 9848:9848  nacos/nacos-server

**Comment by catcherwong** [comment]
这是一个常见问题，可以参见 faq

https://nacos-sdk-csharp.readthedocs.io/en/latest/guide/faq.html
