### ISSUE TITLE
nacos-sdk-csharp.YamlParser 这个存在线程安全问题

### ISSUE THREAD

**Issue by comeonwuzhiliang** [nacos-group/nacos-sdk-csharp#176]

**Comment by catcherwong** [comment]
麻烦给出具体的例子来复现一下，不然很难凭空猜出来。

**Comment by comeonwuzhiliang** [comment]
我就简单说明一下：YamlConfigurationStringParser 这个类的Parse方法存在线程安全问题，因为你这边的本地缓存也会使用这个，而远程listener也会使用这个。两者同时进行就会出现问题。
