### ISSUE TITLE
nacos 2.0.4 grpc服务无法注册

### ISSUE THREAD

**Issue by leehavin** [nacos-group/nacos-sdk-csharp#187]
使用samples中app2示例进行测试，服务端无调整为默认设置，端口号等，开放了9848端口。
使用示例提示注册成功，但是在服务单未发现服务。 但x.NamingUseRpc = false的时候能够正常注册服务。

    x.ServerAddresses = new List<string> { "http://[自己的链接]:8848" };
    x.EndPoint = "";
    x.Namespace = "";  [默认public id为空]
    x.ListenInterval = 1000;
    x.ServiceName = "App2";
    x.GroupName = "DEFAULT_GROUP";
    x.ClusterName = "DEFAULT";
    x.Ip = "";
    x.PreferredNetworks = "";
    x.Port = 0;
    x.Weight = 100;
    x.RegisterEnabled = true;
    x.InstanceEnabled = true;
    x.Ephemeral = true;
    x.Secure = false;
    x.NamingUseRpc = true;  [打开grpc]

nacos server 2.0.4

**Comment by catcherwong** [comment]
看了一下 nacos 那边的源码

http 的，也就是 **NamingUseRpc = false** 时，传了空过去会自动填充默认值。

https://github.com/alibaba/nacos/blob/2e07c6a0c162b5685f86414f0be5ba521a39fa39/naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java#L107-L108

grpc 时，也就是 **NamingUseRpc = true** 时，传了空过去不会自动填充默认值。

https://github.com/alibaba/nacos/blob/2e07c6a0c162b5685f86414f0be5ba521a39fa39/naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/InstanceRequestHandler.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L48-L49

这两个的行为就不一致了。

可以先尝试不使用默认的命名空间，用自建的先测试，我这边同步一下 nacos 那边，确认这个问题

**Comment by catcherwong** [comment]
看了一下 nacos 那边的源码

http 的，也就是 **NamingUseRpc = false** 时，传了空过去会自动填充默认值。

https://github.com/alibaba/nacos/blob/2e07c6a0c162b5685f86414f0be5ba521a39fa39/naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java#L107-L108

grpc 时，也就是 **NamingUseRpc = true** 时，传了空过去不会自动填充默认值。

https://github.com/alibaba/nacos/blob/2e07c6a0c162b5685f86414f0be5ba521a39fa39/naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/InstanceRequestHandler.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L48-L49

这两个的行为就不一致了。

可以先尝试不使用默认的命名空间，用自建的先测试，我这边同步一下 nacos 那边，确认这个问题

**Comment by catcherwong** [comment]
> 使用示例提示注册成功，但是在服务单未发现服务

另外补充一下，这个是因为命名空间不对，导致在控制台那边的页面上没有显示，实际上服务是已经注册到对应的命名空间上面去的了。

**Comment by leehavin** [comment]
@catcherwong  好的，那客户端进行校验还是nacos server来处理，是否客户端适配下，发个新版？😄
