### ISSUE TITLE
how to close log.

### ISSUE THREAD

**Issue by huhu-sky** [nacos-group/nacos-sdk-csharp#188]
while running the svc, there are so much log about  beat. How to close these logs.

**Comment by catcherwong** [comment]
Setting the `LogLevel` for the different categories.

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "Nacos": "Error",
      "Nacos.xxx": "Warning"
    }
  }
}
```

**Comment by huhu-sky** [comment]
> Setting the `LogLevel` for the different categories.
> 
> ```json
> {
>   "Logging": {
>     "LogLevel": {
>       "Default": "Warning",
>       "Nacos": "Error",
>       "Nacos.xxx": "Warning"
>     }
>   }
> }
> ```

Thanks.
