### ISSUE TITLE
.net 6 aspnet api 读取配置失败

### ISSUE THREAD

**Issue by Amber-Wish** [nacos-group/nacos-sdk-csharp#198]
环境：.net 6 + nacos 2.1.0
代码如下：
Program.cs
`builder.Services.AddNacosV2Config(builder.Configuration.GetSection("NacosConfig"));`
----
appsettings.json
`{
  "NacosConfig": {
    "Listeners": [
      {
        "Optional": false,
        "DataId": "common",
        "Group": "DEFAULT_GROUP"
      },
      {
        "Optional": false,
        "DataId": "demo",
        "Group": "DEFAULT_GROUP"
      }
    ],
    "Namespace": "test",
    "ServerAddresses": [
      "http://192.168.240.200:30105"
    ],
    "UserName": "nacos",
    "Password": "nacos",
    "AccessKey": "",
    "SecretKey": "",
    "EndPoint": "",
    "ConfigFilterAssemblies": [
      "MyYarpProxy"
    ],
    "ConfigFilterExtInfo": ""
  }
}`
-----
controller
`public class ConfigController : ControllerBase
{
    private readonly IConfiguration _configuration;

    // GET
    public ConfigController(IConfiguration configuration)
    {
        _configuration = configuration;
    }

    [HttpGet("get")]
    public async Task<string> Get()
    {
        var res = _configuration["demokey"];

        return res ?? "empty config";
    }
}`
----
nacos server 配置
![image](https://user-images.githubusercontent.com/55867470/168249662-02145fa5-501d-4356-8914-2f881001720d.png)
![image](https://user-images.githubusercontent.com/55867470/168249723-0a50c721-d983-48b0-aeae-246daf2f4747.png)

运行的结果为null

**Comment by catcherwong** [comment]
命名空间的问题。

https://nacos-sdk-csharp.readthedocs.io/en/latest/guide/faq.html#id2

**Comment by Amber-Wish** [comment]
@catcherwong 你好，我将配置信息改成如下：
![image](https://user-images.githubusercontent.com/55867470/168322185-f3fcf70f-baba-448c-9682-94f2f7368b85.png)
发现还是不可以获取到变量值。

**Comment by catcherwong** [comment]
日志方便贴一下不？目前提供的信息没办法判断那里有问题。

**Comment by Amber-Wish** [comment]
@catcherwong 请问是指哪里的日志呢？

**Comment by catcherwong** [comment]
应用获取nacos 配置时的日志，看你的示例，应该是应用启动时和nacos交互的日志。

**Comment by Amber-Wish** [comment]
@catcherwong 我的应用启动时，并没有看到有与nacos 产生互动的日志

**Comment by Amber-Wish** [comment]
![image](https://user-images.githubusercontent.com/55867470/168428517-6a8db26d-aec2-4242-81ea-6ee5dfa30e7f.png)
启动后是这样的，没有nacos的日志

**Comment by Amber-Wish** [comment]
用的是这些版本的包
![image](https://user-images.githubusercontent.com/55867470/168428581-d5dd72b0-4abe-4408-b04a-7daa609c087e.png)

**Comment by catcherwong** [comment]
如果可以的话，提供一个脱敏的例子吧，这样看不太出问题

**Comment by Amber-Wish** [comment]
好的，怎么提供给你呢？

**Comment by catcherwong** [comment]
在你的github 创建一个项目，告诉一下地址就可以了。

另外，这个 MsConfigApp 的例子是否已经跑通了？

https://github.com/nacos-group/nacos-sdk-csharp/tree/dev/samples/MsConfigApp

**Comment by Amber-Wish** [comment]
@catcherwong 我尝试你说的那个例子的demo 运行起来后，发生报错：
![image](https://user-images.githubusercontent.com/55867470/175254303-e437f7a1-c6cc-48fc-ba65-ed7e591dc2ad.png)
根据readme 的建议设置的配置信息如下：
![image](https://user-images.githubusercontent.com/55867470/175254503-39c6074f-96f1-4142-937f-948e0a269521.png)
