### ISSUE TITLE
net6 使用nacos获取不到配置

### ISSUE THREAD

**Issue by FLLOVEBT** [nacos-group/nacos-sdk-csharp#199]
这是我的代码和配置
builder.Services.AddNacosV2Config(builder.Configuration.GetSection("Nacos"));
"Nacos": {
    "Listeners": [
      {
        "Optional": false,
        "DataId": "oa.fanlin",
        "Group": "OA_FANLIN_GROUP"
      },
      {
        "Optional": false,
        "DataId": "OA.FanLin",
        "Group": "FANLIN_GROUP"
      }
    ],
    "Optional": false,
    "DataId": "oa.fanlin",
    "Group": "OA_FANLIN_GROUP",
    "Tenant": "b6747850-9ec3-4115-b900-ae4c1919abf2",
    "ServerAddresses": [ "http://192.168.1.4:8848/" ],
    "UserName": "nacos",
    "Password": "nacos",
    "ConfigUseRpc": false,
    "NamingUseRpc": false,
    "ServiceName": "OA.FanLin"
  }

但是获取不到配置信息
![image](https://user-images.githubusercontent.com/37958228/169231776-3d5b9dfb-1b22-4e96-a0a2-242cedf60859.png)

**Comment by catcherwong** [comment]
![image](https://user-images.githubusercontent.com/8394988/169424395-a3a79b05-3e37-4af0-b4ac-4279481427a1.png)

麻烦提供一下有效的信息，有助于排查。

上图是 dev 分支的 sample，基于 .net 6 的了，nacos 用的是 2.1.0 版本。

根据你提供的配置信息调整了之后的运行结果。

**Comment by FLLOVEBT** [comment]
现在最高版本是1.3.2版本。
![image](https://user-images.githubusercontent.com/37958228/169449566-0d7eeca1-375a-4640-a6b2-709838d6f0e0.png)

**Comment by FLLOVEBT** [comment]
![image](https://user-images.githubusercontent.com/37958228/169450215-485390e0-9e1c-4fc2-9e59-655d15a255a5.png)
![image](https://user-images.githubusercontent.com/37958228/169450308-b6f3fa69-b418-4e77-9921-4924fc1854f1.png)
![image](https://user-images.githubusercontent.com/37958228/169450364-2ae170b2-ec9a-4d36-b617-a83bb5dfa89f.png)

**Comment by catcherwong** [comment]
https://github.com/nacos-group/nacos-sdk-csharp/blob/99575dde9dea70d80b2dbe9cd3b4d78a3277196d/samples/MsConfigApp/Program.cs#L17-L38
