### ISSUE TITLE
Unable to get the correct IP in naming service

### ISSUE THREAD

**Issue by Nuan-Yang** [nacos-group/nacos-sdk-csharp#20]
作者您好：
  我发现一个关于服务发现时获取到的ip异常的问题，我的电脑安装了vm虚拟机，所以有两个vm的网络适配器，其中一个的ip为：192.168.80.1，而我本地的真实ip为192.168.109.254，通过nacos-sdk 我获取到了vm的ip地址并发送到了nacos，致使我无法通过网关访问到这个服务。
以上是全部问题，期待您的回答。

------

Hello:

I found a problem about the abnormal ip obtained during service discovery. My computer is installed with a vm virtual machine, so there are two vm network adapters, one of which has an ip: 192.168.80.1, and my local real ip is 192.168.109.254, through nacos-sdk, I obtained the ip address of vm and sent it to nacos, which made me unable to access this service through the gateway.

**Comment by qiuhaohui163** [comment]
在https://github.com/nacos-group/nacos-sdk-csharp/pull/16 中已经解决该问题
在注册服务的配置上加上PreferredNetworks 会取以该前缀开头的网络 
```json
  "nacos": {
     ...
    "PreferredNetworks": "192.168.109",
  }
```

**Comment by catcherwong** [comment]
@Nuan-Yang 

参考 @qiuhaohui163 的回答试试，这个问题已经是修复过的了。

-----

Take a look on the answer of @qiuhaohui163 , this issue was fixed.

**Comment by Nuan-Yang** [comment]
> @Nuan-Yang 
> 
> 参考 @qiuhaohui163 的回答试试，这个问题已经是修复过的了。
> 
> -----
> 
> Take a look on the answer of @qiuhaohui163 , this issue was fixed.
> 
> 
> 
> 

已经正常了，十分感谢。
