### ISSUE TITLE
docker-compose up after down always get the error for config

### ISSUE THREAD

**Issue by MartinHuang126** [nacos-group/nacos-sdk-csharp#200]
![image](https://user-images.githubusercontent.com/50539517/169983630-3769fbfd-be66-432c-877e-fce7947a4335.png)

## Tell us your environment

- nacos-sdk-csharp version: 1.3.2
- modular : config
- nacos server version: 2.0.3
- how to host nacos server : docker

## Anything else we need to know?
just the first up would get error

**Comment by catcherwong** [comment]
Please have a try with version **1.3.3-alpha20220524112507**
