### ISSUE TITLE
以Windows服务运行时，Config客户端缓存目录在程序运行目录

### ISSUE THREAD

**Issue by walter504** [nacos-group/nacos-sdk-csharp#205]
FileLocalConfigInfoProcessor 中 LOCAL_SNAPSHOT_PATH = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "nacos", "config");
Windows服务默认以LocalSystem账号运行，Environment.GetFolderPath(Environment.SpecialFolder.Personal)会返回空字符串，导致Config客户端缓存目录在当前程序运行目录，公共配置无法共用，如果使用Failover将要每个服务单独配置。

在nacos官方文档中环境变量JM.SNAPSHOT.PATH是用来配置Config客户端缓存目录的，但是.NET项目里被用作Naming客户端的缓存目录，是否可以修改成两者都使用JM.SNAPSHOT.PATH作为缓存目录。

**Comment by catcherwong** [comment]
@walter504 谢谢反馈，这个是可以的，需要加一个环境变量的处理即可。

**Comment by catcherwong** [comment]
v1.3.3 处理了这个问题
