### ISSUE TITLE
.net core 3.1 下读取配置文件一直为空

### ISSUE THREAD

**Issue by sbreast** [nacos-group/nacos-sdk-csharp#209]
![image](https://user-images.githubusercontent.com/5645633/173762039-7a0e27ee-12aa-4dbf-8239-02e851d82f4a.png)
![1655276160202](https://user-images.githubusercontent.com/5645633/173762411-35b81ce5-900e-4d5e-9d0e-d13ada31d32f.png)

**Comment by catcherwong** [comment]
详见第二点。

https://nacos-sdk-csharp.readthedocs.io/en/latest/guide/faq.html#nacos-server

**Comment by catcherwong** [comment]
@bingtianyiyan 
> 我使用nacos-sdk-csharp案例里的App3里ConfigController下的Publish发布配置，然后在nacos的配置管理-配置列表查询不到。但是使用Get方法是可以查询的到写入的内容。。
另外一种情况是：我在nacos的配置管理-配置列表 新增测试配置，然后使用ConfigController下的Get方法查询也查询不到。

这种就是命名空间的问题了。值要设置成**命名空间Id**

**Comment by bingtianyiyan** [comment]
确实。可以了，3q。不是命名空间名称而是命名ID，这个有点坑，命名空间Namespace名称本身不能重复为什么x.Namespace却填ID，
