### ISSUE TITLE
RPC connect error on MAC M1 (ARM ISSUE).

### ISSUE THREAD

**Issue by hemiaoio** [nacos-group/nacos-sdk-csharp#211]
## Describe what happened 

 Nacos.V2.Config.NacosConfigService[0]
      async listen config change error 
      Nacos.V2.Exceptions.NacosException: Client not connected,current status: STARTING

## Describe what you expected to happen

I want read the configuration from nacos success.

## How to reproduce it (as minimally and precisely as possible)

Use the following code

## Related code

```JSON
{
  "Nacos": {
      "IsEnabled": true,
      "Listeners": [
        {
          "Optional": false,
          "DataId": "abc",
          "Group": "DEFAULT_GROUP"
        }
      ],
      "Namespace": "4c017b3b-8460-4978-abef-35307a191234",
      "ServerAddresses": [
        "http://192.168.1.1:8848"
      ],
      "UserName": "nacos",
      "Password": "nacos",
      "RegisterEnabled": false,
      "InstanceEnabled": false
    }
}
```

```csharp
var configurationBuilder = new ConfigurationBuilder();

configurationBuilder.AddJsonFile("appsettings.json");

var configuration = configurationBuilder.Build();

configurationBuilder.AddNacosV2Configuration(configuration.GetSection("nacos"));

configuration = configurationBuilder.Build();  // error
```

## Tell us your environment

- nacos-sdk-csharp version: 1.3.3
- modular : Nacos.Microsoft.Extensions.Configuration
- nacos server version: 2.0.3
- how to host nacos server : docker

## Anything else we need to know?

Operate System : macOS 12.4
Hardware：CPU M1 (ARM 64)

On Windows platform ,it was worked successfully.

**Comment by catcherwong** [comment]
> Client not connected,current status: STARTING

For this issue, take a look on faq 

https://nacos-sdk-csharp.readthedocs.io/en/latest/guide/faq.html

**Comment by hemiaoio** [comment]
Thank you for this issue .
Can it be understood that HTTP is used on the windows platform? Using RPC on other platforms? The same code, just change a system to run, it failed...

**Comment by catcherwong** [comment]
@hemiaoio  This is an issue for arm when using Grpc.Core. We are using v2.34.1 than can not run on arm. 

After v2.37.0, it works well, so we should upgrade it the newest version.

**Comment by catcherwong** [comment]
#212 has done this issue.

Please have a try with version **1.3.4-alpha20220703021644**

**Comment by xiongjx** [comment]
> > Client not connected,current status: STARTING
> 
> For this issue, take a look on faq
> 
> https://nacos-sdk-csharp.readthedocs.io/en/latest/guide/faq.html

Mac 13.2.1
M1
Nacos 2.2.0 slim Docker
1.3.4 实测还是这个现象(VS For Mac或者Docker部署现象相同)，同样代码在Docker中部署运行正常，在一台Windows开发环境下正常，另外一台Windows开发环境下获取不到配置

**Comment by Cherry542** [comment]
> @hemiaoio 这是使用 Grpc.Core 时 arm 的问题。我们使用的是 v2.34.1，无法在 arm 上运行。
> 
> v2.37.0以后运行良好，应该升级到最新版本。

请问2.37.0  是那个的版本NACOS的版本？NACOS最新的对外能用的版本不是2.2.2吗？.NET CORE 的SDK应该是1.3.5吗？另外M1的MAC 也无法使用DOCKER 方式安装就按你们官方步骤来 都要无法安装。MAC 一只有GRPC默认在MAC下有问题 需要特殊除了，你们最新的1.3.5也确实 无法访问，不信我可以上传源码你在m1或者m2的Mac上试。。。

**Comment by heqingpan** [comment]
.net core sdk不支持m1芯片的原因是因为sdk grpc底层使用的是Grpc.Core，Grpc.Core不支持macOS arm64芯片。

Grpc.Core不支持macOS arm64的原因是因为：Grpc.Core依赖native动态库，然后Grpc.Core包中没有macOS arm64对应的动态库。（windows支持x86和x64,linux支持x64和arm64,macOS只支持x64）


解决方案：

1. 联系Grpc.Core开发者，让其发布支持macOS arm64的新版本；目前Grpc.Core已不更新，其推荐使用grpc-dotnet。
2. 使用grpc-dotnet替换Grpc.Core ，我在本地测试grpc-dotnet的例子，其打包出的结果不依赖native动态库，也就没有grpc-dotnet的问题。 

我看 #258 也有讨论切换到grpc-dotnet，Grpc.Core已不更新，切换到grpc-dotnet的方案应该更合适一些。

----

Grpc.Core不支持macOS arm64，从应用发布结果就能看出来。

使用当前仓库的[samples/App3](https://github.com/nacos-group/nacos-sdk-csharp/tree/dev/samples/App3)例子，在`samples/App3`目录下执行发布命令`dotnet publish`,在 public目录下有runtimes native 动态库包，有5类动态库，不包含osx-arm64 。

发布包文件夹下具体的文件信息如下：

```
$ tree .
.
├── App3
├── App3.deps.json
├── App3.dll
├── App3.pdb
├── App3.runtimeconfig.json
├── App3.xml
├── Google.Protobuf.dll
├── Grpc.Core.Api.dll
├── Grpc.Core.dll
├── Microsoft.Extensions.DependencyModel.dll
├── Nacos.AspNetCore.dll
├── Nacos.AspNetCore.pdb
├── Nacos.AspNetCore.xml
├── Nacos.dll
├── Nacos.pdb
├── Nacos.xml
├── Newtonsoft.Json.dll
├── appsettings.Development.json
├── appsettings.json
├── runtimes
│   ├── linux-arm64
│   │   └── native
│   │       └── libgrpc_csharp_ext.arm64.so
│   ├── linux-x64
│   │   └── native
│   │       └── libgrpc_csharp_ext.x64.so
│   ├── osx-x64
│   │   └── native
│   │       └── libgrpc_csharp_ext.x64.dylib
│   ├── win-x64
│   │   └── native
│   │       └── grpc_csharp_ext.x64.dll
│   └── win-x86
│       └── native
│           └── grpc_csharp_ext.x86.dll
└── web.config


```
