### ISSUE TITLE
Nacos.AspNetCore 为什么不支持netstandard

### ISSUE THREAD

**Issue by knowyi** [nacos-group/nacos-sdk-csharp#216]
你好，请问为什么服务注册的组件 不支持netstandard？

**Comment by knowyi** [comment]
> 你好，请问 我原先有个自己封装的http请求组件 是用的netstandard 方便其他微服务集成发包提供请求的client 现在想接入注册发现通过服务发现来替代 传入url 目前不支持standard 我应该怎么处理 获取源代码编译一个standard的版本？还是有更好的方法

**Comment by knowyi** [comment]
之前有部分服务使用eureka 现在想迁移nacos eureka组件有个GetLocalServiceInstance方法 可以获取本地当前服务的实例 nacos的组件我没看到类似方法 请问有办法可以获取当前实例吗？

**Comment by catcherwong** [comment]
> 我原先有个自己封装的http请求组件

这个应该直接用 raw sdk，基于 **INacosNamingService** 去扩展。

**Comment by knowyi** [comment]
> > 我原先有个自己封装的http请求组件
> 
> 这个应该直接用 raw sdk，基于 **INacosNamingService** 去扩展。

raw sdk是什么没看懂？

**Comment by knowyi** [comment]
> > eureka组件有个GetLocalServiceInstance方法 可以获取本地当前服务的实例
> 
> 这个的用途是什么？

这个是我们有个分布式调度的服务 执行端需要获取自己的服务的信息往调度中心去注册 之前基于eureka实现的 现在我想迁移nacos

**Comment by catcherwong** [comment]
> raw sdk是什么没看懂？

raw sdk 指的就是就原始的 sdk，也就是  https://www.nuget.org/packages/nacos-sdk-csharp

你标题中提到的是 https://www.nuget.org/packages/nacos-sdk-csharp.AspNetCore  ，一个基于 原始 sdk 做了服务注册的包。

**Comment by catcherwong** [comment]
> 执行端需要获取自己的服务的信息往调度中心去注册 

自己的服务信息，都是你自己往上面注册的了，还需要从注册中心拿 ？

**Comment by knowyi** [comment]
> > 执行端需要获取自己的服务的信息往调度中心去注册
> 
> 自己的服务信息，都是你自己往上面注册的了，还需要从注册中心拿 ？

从ek获取当前服务器实例去注册 然后调度中心会从ek来判断 实例的状态是不是可用

**Comment by catcherwong** [comment]
这个时候，调度中心选其中一个 health 状态的实例不就可以了吗？

**Comment by catcherwong** [comment]
可以看看这个，nacos sdk 针对 naming 模块开放的方法。

https://github.com/alibaba/nacos/blob/develop/api/src/main/java/com/alibaba/nacos/api/naming/NamingService.java

**Comment by MartinHuang126** [comment]
@knowyi 我也遇到同样问题，我的处理方法是定义一个接口在standard，实现类在net core 3.1，并引用nacos。将需要nacos相关的方法通过接口代理暴露
