### ISSUE TITLE
I got a long IP mix with the port

### ISSUE THREAD

**Issue by yeahe83** [nacos-group/nacos-sdk-csharp#218]
服务发现的上来的IP不正常，似乎和端口接上了。请教如何排查原因。
<img width="547" alt="ab6c831cfdb4a6ce39b29ccb87cd278" src="https://user-images.githubusercontent.com/9261385/181059859-90c52d5f-6024-4c0f-978d-969835a040ae.png">

nacos v1.4.1
nacos-sdk-csharp-unofficial.AspNetCore v0.8.5

**Comment by catcherwong** [comment]
你是用了 docker 部署的应用吧，注意网段的问题。

另外，unofficial 的包已经不在维护了，尽快切换到不带 unofficial 的包吧。

**Comment by catcherwong** [comment]
参考 #186

**Comment by yeahe83** [comment]
@catcherwong  你好。部署环境是私有云的k8s容器服务。

因为nacos版本是v1，所以我还特地把sdk降回到了unofficial。我是否对sdk的版本理解有误。目前支持v1的最后一个版本是不是0.8.5呢。

IP的问题，172.0.11.170应该就是容器的IP，但是后面最后一节变成了 .17080 就十分奇怪，gateway找不到了。我怎么重启容器新IP都会带一个80在后面。:)

![微信图片_20220727225703](https://user-images.githubusercontent.com/9261385/181280062-8f8faa98-b74e-400d-b142-edd9a9c6f219.jpg)

**Comment by yeahe83** [comment]
@catcherwong  你好。部署环境是私有云的k8s容器服务。

因为nacos版本是v1，所以我还特地把sdk降回到了unofficial。我是否对sdk的版本理解有误。目前支持v1的最后一个版本是不是0.8.5呢。

IP的问题，172.0.11.170应该就是容器的IP，但是后面最后一节变成了 .17080 就十分奇怪，gateway找不到了。我怎么重启容器新IP都会带一个80在后面。:)

![微信图片_20220727225703](https://user-images.githubusercontent.com/9261385/181280062-8f8faa98-b74e-400d-b142-edd9a9c6f219.jpg)

**Comment by catcherwong** [comment]
> 因为nacos版本是v1，所以我还特地把sdk降回到了unofficial。我是否对sdk的版本理解有误。目前支持v1的最后一个版本是不是0.8.5呢。

sdk 1.x 可以同时支持 nacos server 1.x 和 2.x 的。

> IP的问题，172.0.11.170应该就是容器的IP，但是后面最后一节变成了 .17080 就十分奇怪，gateway找不到了。我怎么重启容器新IP都会带一个80在后面。:)

这个看上去是直接把 80 拼接到 IP 上面去了。先尝试升级到最新版本的 sdk 试试吧。

**Comment by catcherwong** [comment]
如果方便的话，也贴一下脱敏后的环境变量、启动参数和配置文件，我这边看看能不能复现

**Comment by yeahe83** [comment]
谢谢老黄的帮助。这次是我配置环境变量时把 ASPNETCORE_URLS 写错了，端口前少了一个冒号。 开心收工。
