### ISSUE TITLE
时常碰到IOException

### ISSUE THREAD

**Issue by MartinHuang126** [nacos-group/nacos-sdk-csharp#220]
## Describe what you expected to happen

![image](https://user-images.githubusercontent.com/50539517/182751020-a5f182b4-6c3b-4e02-add7-1c6e18ce6142.png)

## Tell us your environment

- nacos-sdk-csharp version: [e.g. 1.3.3]
- modular : [e.g. naming]
- nacos server version: [e.g. 2.0.3]
- how to host nacos server : [e.g. docker]

## Anything else we need to know?
怀疑是否和心跳有关，未找到心跳配置参数，五秒是否太频繁。没有使用grpc。

**Comment by catcherwong** [comment]
这个就是请求超时了。

nacos client 和 nacos server 交互用 grpc 和你应用本身是否用 grpc 是没有必然联系的。

**Comment by MartinHuang126** [comment]
能否提供心跳间隔参数，目前发现是并发高时经常会碰到这个超时，nacos client 和 nacos server 交互使用的是http

**Comment by catcherwong** [comment]
心跳的间隔，是取决于 beat 接口返回的 `clientBeatInterval`.

```json
{
        "clientBeatInterval": 5000,
        "code": 10200,
        "lightBeatEnabled": true
}
```

这个参数，可以在注册服务时，在 metadata 中添加 一个 **preserved.heart.beat.interval** 的参数来指定，如果没有指定，默认就是5s。

但是要注意，这个参数设置的值，不能大于 **preserved.heart.beat.timeout** 的设定值或默认值 15s。

**Comment by MartinHuang126** [comment]
感谢，preserved.heart.beat.interval能控制心跳间隔。
但是我看源码 preserved.heart.beat.timeout 是没有引用的。是否为nacos service 控制

**Comment by catcherwong** [comment]
**preserved.heart.beat.timeout** 是服务端的逻辑，客户端可以用这个调整对应逻辑的值判断。

**Comment by MartinHuang126** [comment]
感谢
