### ISSUE TITLE
NET6使用nacos-sdk-csharp1.3.2服务发现问题

### ISSUE THREAD

**Issue by kongqqiang824362967** [nacos-group/nacos-sdk-csharp#225]
.net6.0 nacos2.0.3 
请问在NET6中使用nacos-sdk-csharp1.3.2在进行服务发现的时候出现一个问题，在nacos管理界面服务都在，但是使用SelectOneHealthyInstance查询服务的时候，只能查询.netCore的服务，java的服务为空。

**Comment by catcherwong** [comment]
如果服务下面有健康状态的实例，是可以查询出来的，不应该查不出来才对。

可以提供更具体一点的信息吗？

**Comment by kongqqiang824362967** [comment]
谢谢，我们通过看源码了解，是因为我集群的时候，命名的大小写出问题了，看调试源码发现问题了，谢谢。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nacos-group/nacos-sdk-csharp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月12日(星期五) 下午4:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nacos-group/nacos-sdk-csharp] NET6使用nacos-sdk-csharp1.3.2服务发现问题 (Issue #225)





 
如果服务下面有健康状态的实例，是可以查询出来的，不应该查不出来才对。
 
可以提供更具体一点的信息吗？
