### ISSUE TITLE
优先使用本地配置 问题

### ISSUE THREAD

**Issue by Yang-XL** [nacos-group/nacos-sdk-csharp#228]
## Describe what happened (or what feature you want)

配置中心 
方法： private async Task<string> GetConfigInner(string tenant, string dataId, string group, long timeoutMs)
总是优先使用本地配置

目前出现的问题是  如果我在更改配置的同时 停止了服务，则我再次启动服务 无法使用最新的配置

## Describe what you expected to happen

建议提供方法重写或者提供重载 可以直接读取数据源

## How to reproduce it (as minimally and precisely as possible)
更改配置的同时 停止了服务，然后重启，

## Tell us your environment

- nacos-sdk-csharp version: 1.3.3

## Anything else we need to know?

建议方法提供重载或 使用 TryAddSingleton  开放组件的重写功能。也方便开发者进行一些定制化的重写

本地配置是否应该作为 备份 或容灾（可快速从本地还原到新的集群）。

**Comment by catcherwong** [comment]
>方法： private async Task GetConfigInner(string tenant, string dataId, string group, long timeoutMs)
>总是优先使用本地配置

这里可能有个误区，读取配置的顺序是 Failover -> query from server -> Snapshot。

这里优先的是 Failover ，可以理解成是容灾的(1. 客户端紧急重启；2. 服务端挂了的时候又想改配置)，正常是人为处理的。

正常 Failover 都是为空，直接跳过，走 实时查询的。

实时查询失败后，会从上次成功查询后写入的 snapshot 中读取配置，确保可用。

------

> 目前出现的问题是 如果我在更改配置的同时 停止了服务，则我再次启动服务 无法使用最新的配置

这个有示例代码可以看看吗？我这边没办法复现这个问题，重启应用后都是获取到最新的配置。

------

> 建议提供方法重写或者提供重载 可以直接读取数据源

这个就应用场景来看，意义不大，暂时不考虑。

**Comment by Yang-XL** [comment]
> > 方法： private async Task GetConfigInner(string tenant, string dataId, string group, long timeoutMs)
> > 总是优先使用本地配置
> 
> 这里可能有个误区，读取配置的顺序是 Failover -> query from server -> Snapshot。
> 
> 这里优先的是 Failover ，可以理解成是容灾的(1. 客户端紧急重启；2. 服务端挂了的时候又想改配置)，正常是人为处理的。
> 
> 正常 Failover 都是为空，直接跳过，走 实时查询的。
> 
> 实时查询失败后，会从上次成功查询后写入的 snapshot 中读取配置，确保可用。
> 
> > 目前出现的问题是 如果我在更改配置的同时 停止了服务，则我再次启动服务 无法使用最新的配置
> 
> 这个有示例代码可以看看吗？我这边没办法复现这个问题，重启应用后都是获取到最新的配置。
> 
> > 建议提供方法重写或者提供重载 可以直接读取数据源
> 
> 这个就应用场景来看，意义不大，暂时不考虑。

后来有没办法重现了。 不确定是不是偶发或者是我的误操作。
大致的步骤是 
我配置了一些XML格式的配置。在程序启动的时候读取。因为启动的时候发现我的配置有问题 我就随便停了下来。改了配置 发布之后直接启动了项目（调试状态），断点看到的是未更正之前的数据。后续没有再出现过。

谢谢及时回复。 我后续会持续跟踪 有问题的话 会记录清楚再请教你
