### ISSUE TITLE
Support for non-service providers to access nacos naming service

### ISSUE THREAD

**Issue by inversionhourglass** [nacos-group/nacos-sdk-csharp#235]
## Describe what happened (or what feature you want)

非webapi/mvc应用通过`IServiceCollection.AddNacosAspNet`注册nacos后，启动会报无法获取`IServer`
> System.InvalidOperationException: 'Unable to resolve service for type 'Microsoft.AspNetCore.Hosting.Server.IServer' while attempting to activate 'Nacos.AspNetCore.V2.RegSvcBgTask'.'

在手动创建一个`MockServer`进行注册后，可以消除前面`IServer`的报错，但如果不传入`ServiceName`，`PreferredNetworks`和`Port`参数，在应用启动时会输出三次错误日志

> fail: Nacos.AspNetCore.V2.RegSvcBgTask[0]
      register instance error, count = 3
      System.ArgumentException: Param 'serviceName' is illegal, serviceName is blank
         at Nacos.V2.Naming.Utils.NamingUtils.GetGroupedName(String serviceName, String groupName)
         at Nacos.V2.Naming.Remote.Grpc.NamingGrpcRedoService.CacheInstanceForRedo(String serviceName, String groupName, Instance instance)
         at Nacos.V2.Naming.Remote.Grpc.NamingGrpcClientProxy.RegisterServiceAsync(String serviceName, String groupName, Instance instance)
         at Nacos.V2.Naming.Remote.NamingClientProxyDelegate.RegisterServiceAsync(String serviceName, String groupName, Instance instance)
         at Nacos.V2.Naming.NacosNamingService.RegisterInstance(String serviceName, String groupName, Instance instance)
         at Nacos.AspNetCore.V2.RegSvcBgTask.StartAsync(CancellationToken cancellationToken)

## Describe what you expected to happen

有一些不提供服务的应用也需要通过nacos调用其他服务，希望可以提供一种方式可以不进行服务注册来使用`INacosNamingService`

## Related code

```csharp
internal class MockServer : IServer
{
    public IFeatureCollection Features => FeatureCollection.Instance;

    public void Dispose()
    {
        // ignore
    }

    public Task StartAsync<TContext>(IHttpApplication<TContext> application, CancellationToken cancellationToken)
        where TContext : notnull
    {
        return Task.CompletedTask;
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }

    private class FeatureCollection : Dictionary<Type, object>, IFeatureCollection
    {
        public static readonly FeatureCollection Instance = new();

        public bool IsReadOnly => true;

        public int Revision => 0;

        public TFeature? Get<TFeature>()
        {
            return default;
        }

        public void Set<TFeature>(TFeature? instance)
        {
            // ignore
        }
    }
}

class TestService : IHostedService
{
    private readonly INacosNamingService _namingService;

    public TestService(IServiceProvider provider)
    {
        _namingService = provider.GetRequiredService<INacosNamingService>();
    }

    public async Task StartAsync(CancellationToken cancellationToken)
    {
        var instances = await _namingService.GetAllInstances("store-api-servicehost");
        Console.WriteLine(instances.Count);
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }
}

internal class Program
{
    static Task Main(string[] args)
    {
        return Host
                .CreateDefaultBuilder()
                .ConfigureServices(services =>
                {
                    services.AddNacosAspNet(options =>
                    {
                        options.EndPoint = "1.2.3.4:8080";
                        options.Namespace = "public";
                        options.UserName = "nacos";
                        options.Password = "nacos";

                        // options.ServiceName = "test";
                        // options.PreferredNetworks = "10.10.110.100";
                        // options.Port = 2345;
                    });
                    services.AddHostedService<TestService>();
                    // services.AddSingleton<IServer, MockServer>();
                })
                .RunConsoleAsync();
    }
}
```

## Tell us your environment

- nacos-sdk-csharp version: 1.3.4

**Comment by catcherwong** [comment]
直接使用 **AddNacosV2Naming** 即可。

https://github.com/nacos-group/nacos-sdk-csharp/blob/9a700ad62ef9af0d751c293476f7fc27e20df08f/samples/App3/Program.cs#L21-L29

**Comment by inversionhourglass** [comment]
确实，我没注意到
