### ISSUE TITLE
NacosV2Configuration希望可以同时添加多个服务

### ISSUE THREAD

**Issue by jovi-Li** [nacos-group/nacos-sdk-csharp#236]
NacosV2Configuration配置
方法AddNacosAspNet 
例如 不知道为什么某个服务 需要-提供 http请求入口，grpc请求入口，和rpc请求入口，

**Comment by jovi-Li** [comment]
另外希望能支持header路由，因为grpc-web路径路由有问题

**Comment by catcherwong** [comment]
没看懂表达的问题是什么意思。

是用配置的时候有问题，还是用服务注册发现的时候有问题

**Comment by jovi-Li** [comment]
服务发现

**Comment by jovi-Li** [comment]
一个程序需要注意多个服务，一个是http监听服务，一个grpc的监听，可能还有一个rpc的监听    ，另外，因为grpc通过路径路由有问题（旧程序使用http1的场景)，所以不能走path路由，我测试可以通过head路由

**Comment by catcherwong** [comment]
你的这种情况，有两个解决方案。

1. 使用原生的 sdk，不使用 AddNacosAspNet，这样你可以在同一个程序中注册任意多个服务到 nacos 上面。
2. 如果这个程序注册的多个服务，

2.1 它们的服务名是一样的，那么你可以用 **元数据** 的方式来丰富你的场景。在元数据中添加 grpc 端口， rpc端口，甚至是 IP 等信息，调用方在调用的时候就可以随意选择对应的方式；
2.1 它们的服务名不一样，那么建议拆分服务，把这多个服务放到不同的程序里面。

**Comment by jovi-Li** [comment]
可以用元数据， 那我改你的nacos那个extension的代码，nacos sdk不用动 3q
