### ISSUE TITLE
配置多地址注册只有第一个地址被注册上

### ISSUE THREAD

**Issue by lovexian** [nacos-group/nacos-sdk-csharp#239]
我在项目的注册配置里添加了两个注册地址,但是只有第一个生效了,第二个地址服务并没有被注册上,请问是什么原因?
配置如下:
  "nacos": {
    "ServerAddresses": [
      "http://cloudXXX.cn:8848/",
      "http://nacosXXX.cn:8848/"
    ],
    "RegisterEnabled": true
}

- nacos-sdk-csharp version: 1.3.3
- nacos server version: 2.1.0
- how to host nacos server : docker/k8s

**Comment by catcherwong** [comment]
你这是两个集群？

**Comment by lovexian** [comment]
是的,我想向两个集群同时注册服务

**Comment by catcherwong** [comment]
你这个需求需要自己做一层定制，目前的 **nacos-sdk-csharp.AspNetCore** 只支持单集群。

你可以基于 **nacos-sdk-csharp**，在应用启动的时候，获取到服务信息，然后调用 **RegisterInstance** 方法，向两个集群都注册。

**Comment by lovexian** [comment]
好的,谢谢解答

**Comment by catcherwong** [comment]
ServerAddresses 里面放的就是单个集群的节点。
