### ISSUE TITLE
服务注册的端口不正确的问题

### ISSUE THREAD

**Issue by 1378955720** [nacos-group/nacos-sdk-csharp#240]
环境：.net6，VS2022，nacos-sdk-csharp版本为1.3.4；
条件：不在nacos配置指定port配置；
问题：在VS2022启动项目的情况下，nacos服务注册能得到服务监听的port；但是用dotnet、dotnet run命令启动项目的时候，nacos服务注册得不到正确的服务监听的port，得到的port永远为80
案例：运行dotnet run environment=Development urls=http://localhost:5100，内容如下图
![Image_20221213115640](https://user-images.githubusercontent.com/39641396/207223029-ebeb3d77-a1cf-41da-ba9a-95401c08ee50.jpg)

**Comment by catcherwong** [comment]
参考一下这个 issue #106

**Comment by 1378955720** [comment]
已解决，非常感谢！
