### ISSUE TITLE
服务docker部署服务注册网段不一致

### ISSUE THREAD

**Issue by knowyi** [nacos-group/nacos-sdk-csharp#241]
你好，我使用的docker部署的微服务 遇到的网段不一致的问题
![image](https://user-images.githubusercontent.com/7392434/215453285-8b9a129c-3df6-406d-a61c-e131b87efd80.png)
请问这个应该如何比较好的解决？是设置docker网段吗？
如果我同一个宿主机部署多个服务端口不一样应该如何配置appseeting的Port？ 是可以从ASPNETCORE_URLS中获取吗

**Comment by catcherwong** [comment]
> 遇到的网段不一致的问题

网段问题的话可以指定 **PreferredNetworks** 。

> 如果我同一个宿主机部署多个服务端口不一样应该如何配置appseeting的Port？ 是可以从ASPNETCORE_URLS中获取吗

容器化部署的话，可以用 ASPNETCORE_URLS 来设置应用端口。

**Comment by knowyi** [comment]
> > 遇到的网段不一致的问题
> 
> 网段问题的话可以指定 **PreferredNetworks** 。
> 
> > 如果我同一个宿主机部署多个服务端口不一样应该如何配置appseeting的Port？ 是可以从ASPNETCORE_URLS中获取吗
> 
> 容器化部署的话，可以用 ASPNETCORE_URLS 来设置应用端口。

感谢 容器端口 设置ASPNETCORE_URLS 可以解决

网段问题有点不懂还想咨询一下 我目前正常网段是192.168开头 容器部署以后IP只有172.17开头的 我是需要先设置容器ip分配192.168的网段吗？

**Comment by catcherwong** [comment]
> 网段问题有点不懂还想咨询一下 我目前正常网段是192.168开头 容器部署以后IP只有172.17开头的 我是需要先设置容器ip分配192.168的网段吗？

假设 宿主机网段是 192.168 ，容器的是172.17

如果想注册到nacos的实例IP 是 192.168.x.x 的话， 可以设置 PreferredNetworks 为 192.168

**Comment by knowyi** [comment]
我之前试过了设置PreferredNetworks 为 192.168 但是注册的IP是127.0.0.1
![image](https://user-images.githubusercontent.com/7392434/215653636-fbccccea-021d-4ce1-9aa0-e3d6b6a59657.png)
这是appsetting的配置
"nacos": {
    "ServerAddresses": [ "http://192.168.103.126:9848" ],
    "DefaultTimeOut": 30000,
    "Namespace": "Test",
    "ListenInterval": 30000,
    "ServiceName": "file.iapi.mykeying.com",
    "PreferredNetworks": "192.168",
    "Listeners": [
      {
        "DataId": "KeyingFileApi.Config",
        "Group": "Base",
        "IsListeners": true
      }
    ]
  }

**Comment by catcherwong** [comment]
注册上去变成 127.0.0.1 的话，是获取应用IP 这个没有成功获取到才会降级程 127.0.0.1。
