### ISSUE TITLE
k8s部署nacos，客户端无法连接

### ISSUE THREAD

**Issue by ethan-shan** [nacos-group/nacos-sdk-csharp#242]
{
  "NacosConfig": {
    "Listeners": [
      {
        "Optional": false,
        "DataId": "DemoConfig",
        "Group": "DEFAULT_GROUP"
      }
      //{
      //  "Optional": false,
      //  "DataId": "demo",
      //  "Group": "DEFAULT_GROUP"
      //}
    ],
    "Namespace": "DemoSystem", // Please set the value of Namespace ID !!!!!!!!
    "ServerAddresses": [ "nacos-headless.default.svc.cluster.local:8848" ], //serve_name.namespace.svc.cluster.local
    "UserName": "",
    "Password": ""
  }
}

**Comment by catcherwong** [comment]
具体报错是什么？
