### ISSUE TITLE
新版本查询群组下所有服务的问题

### ISSUE THREAD

**Issue by lycoris-xmin** [nacos-group/nacos-sdk-csharp#243]
- nacos-sdk-csharp version:1.3.4

![8965c1215d9bebaa54bf91b62d45ff11](https://user-images.githubusercontent.com/43264181/230899846-8a500230-14c6-4b31-9b40-d28823e3a27b.png)

![iwEcAqNwbmcDAQTRBUkF0QJIBrChzwquiq4WNwQsY3L5wIUAB9JwCuGqCAAJomltCgAL0gAA7HQ png_620x10000q90](https://user-images.githubusercontent.com/43264181/230899888-7ad9cc79-dd83-4124-bfa7-66dd6d051476.jpg)

![925d71db0ae1c5e4bde41695751cbc323140ef48e9fdb04f7cd3bf2aed0bdc2bQzpcVXNlcnNcbHljb3Jpc1xBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMTg3OTc2MTMyMl92MlxJbWFnZUZpbGVzXDE2ODExMjg3OTAzODJfNjIxRDFGRDctM0I0OC00YzdlLUE3QzAtNEIwMTg4MjU5M0NFLnBuZw==](https://user-images.githubusercontent.com/43264181/230899894-dcb2d608-fb78-4580-a26e-6e14adaf067e.png)

**Comment by lycoris-xmin** [comment]
Source: INacosNamingService.GetServicesOfServer

**Comment by catcherwong** [comment]
方便提个 PR 过来修复吗？

**Comment by lycoris-xmin** [comment]
@catcherwong  好，我顺带咨询一下，AK,SK连接方式是不是不支持，昨天刚买的mse AK,SK登录一直失败，403 验签失败。我似乎也没有找到你们AK SK的连接规则说明和加密规则，问客服就说只要AK\SK填了就行
