### ISSUE TITLE
.net core SDK调用Nacos报错

### ISSUE THREAD

**Issue by Cherry542** [nacos-group/nacos-sdk-csharp#249]
## .net Sdk调用nacos报错

报错启动报错异常：```
 fail: Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider[0]
      Load config error
      System.ArgumentNullException: Value cannot be null. (Parameter 's')
         at System.IO.StringReader..ctor(String s)
         at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.ParseString(String input)
         at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.Parse(String input)
         at Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider.Load()

```

## 环境依赖：
nacos：2.2.2 
安装方式docker compose 按官方教程
阿里云服务器部署，开放有端口8848,9848

- nacos-sdk-csharp  v1.3.5
- nacos-sdk-csharp.AspNetCore v1.3.5
- nacos-sdk-csharp.Extensions.Configuration v1.3.5

配置文件：
```JSON{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "NacosConfig": {
    "Listeners": [
      {
        "Optional": false,
        "DataId": "demo",
        "Group": "global"
      }

    ],
    "Namespace": "dev",
    "ServerAddresses": [ "http://xx.xx.57.xx:8848/" ],//阿里云服务器开放了端口 8848 ，9848
    "UserName": "nacos",
    "Password": "nacos"
  }
}```

## How to reproduce it (as minimally and precisely as possible)

## 代码如下：



```csharp

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Host.UseNacosConfig(section: "NacosConfig");



var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
```

**Comment by catcherwong** [comment]
这个报错是从 nacos 获取到的配置为空。

检查一下 **Namespace** 的配置值，要是 namespaceid 。

**Comment by Cherry542** [comment]
> 这个报错是从 nacos 获取到的配置为空。
> 
> 检查一下 **Namespace** 的配置值，要是 namespaceid 。

是用的namespaceid

**Comment by Cherry542** [comment]
同样的代码 我换到windows上就可以正常运行，而在我的m1 版本的MAC上 就死活不行

**Comment by wangchaoit** [comment]
按照 catcherwong 的意思
 "Namespace": "dev",  这里 要用命名空间Id    “namespace": "95729e2e-e818-4e43-a60c-a38701a8bf6c"  换成你的GUID  ；

我也遇到了你这个问题 但是我换成 命名空间Id 实际上还是跟楼主报一样的错误，不知道该怎么解决

**Comment by cethink** [comment]
遇到同样的问题，换成Id就可以了，谢谢

**Comment by catcherwong** [comment]
mac m1~m3 的问题，请使用最新的 1.3.9 版本
