### ISSUE TITLE
.net core sdk 在 M1芯片的mac下面grpc 无法连接的bug

### ISSUE THREAD

**Issue by Cherry542** [nacos-group/nacos-sdk-csharp#250]
在m1芯片下不管配置中心，还是注册发现 都会报错：fail: Nacos.V2.Config.NacosConfigService[0]
      async listen config change error 
      Nacos.V2.Exceptions.NacosException: Client not connected,current status: STARTING
         at Nacos.V2.Remote.RpcClient.Request(CommonRequest request, Int64 timeoutMills)
         at Nacos.V2.Config.Impl.ConfigRpcTransportClient.RequestProxy(RpcClient rpcClientInner, CommonRequest request, Int64 timeout)
         at Nacos.V2.Config.Impl.ConfigRpcTransportClient.ExecuteConfigListen()
  ；但是同样的代码到windows上 立马正常， 不知道会不会和[ 无法在 macOS 上启动 ASP.NET Core gRPC 应用](https://learn.microsoft.com/zh-cn/aspnet/core/grpc/troubleshoot?view=aspnetcore-6.0)  描述的问题有关系

**Comment by catcherwong** [comment]
sdk 这块是支持 m1 芯片的，

```
Client not connected,current status: STARTING
```

这个错误参考一下这个

https://nacos-sdk-csharp.readthedocs.io/en/latest/guide/faq.html#nacos-server

**Comment by heqingpan** [comment]
.net core sdk不支持m1芯片的原因是因为sdk grpc底层使用的是Grpc.Core，Grpc.Core不支持macOS arm64芯片。

Grpc.Core不支持macOS arm64的原因是因为：Grpc.Core依赖native动态库，然后Grpc.Core包中没有macOS arm64对应的动态库。（windows支持x86和x64,linux支持x64和arm64,macOS只支持x64）


解决方案：

1. 联系Grpc.Core开发者，让其发布支持macOS arm64的新版本；目前Grpc.Core已不更新，其推荐使用grpc-dotnet。
2. 使用grpc-dotnet替换Grpc.Core ，我在本地测试grpc-dotnet的例子，其打包出的结果不依赖native动态库，也就没有grpc-dotnet的问题。 

我看 #258 也有讨论切换到grpc-dotnet，Grpc.Core已不更新，切换到grpc-dotnet的方案应该更合适一些。

----

Grpc.Core不支持macOS arm64，从应用发布结果就能看出来。

使用当前仓库的[samples/App3](https://github.com/nacos-group/nacos-sdk-csharp/tree/dev/samples/App3)例子，在`samples/App3`目录下执行发布命令`dotnet publish`,在 public目录下有runtimes native 动态库包，有5类动态库，不包含osx-arm64 。

发布包文件夹下具体的文件信息如下：

```
$ tree .
.
├── App3
├── App3.deps.json
├── App3.dll
├── App3.pdb
├── App3.runtimeconfig.json
├── App3.xml
├── Google.Protobuf.dll
├── Grpc.Core.Api.dll
├── Grpc.Core.dll
├── Microsoft.Extensions.DependencyModel.dll
├── Nacos.AspNetCore.dll
├── Nacos.AspNetCore.pdb
├── Nacos.AspNetCore.xml
├── Nacos.dll
├── Nacos.pdb
├── Nacos.xml
├── Newtonsoft.Json.dll
├── appsettings.Development.json
├── appsettings.json
├── runtimes
│   ├── linux-arm64
│   │   └── native
│   │       └── libgrpc_csharp_ext.arm64.so
│   ├── linux-x64
│   │   └── native
│   │       └── libgrpc_csharp_ext.x64.so
│   ├── osx-x64
│   │   └── native
│   │       └── libgrpc_csharp_ext.x64.dylib
│   ├── win-x64
│   │   └── native
│   │       └── grpc_csharp_ext.x64.dll
│   └── win-x86
│       └── native
│           └── grpc_csharp_ext.x86.dll
└── web.config


```

**Comment by hzy-6** [comment]
这个问题还有救吗？

**Comment by catcherwong** [comment]
mac m1~m3 的问题，请使用最新的 1.3.9 版本
