### ISSUE TITLE
xxxx.exe --urls "http://*:5000"  报错

### ISSUE THREAD

**Issue by zhengguojing** [nacos-group/nacos-sdk-csharp#253]
## Describe what happened (or what feature you want)

本地VS调试正常，但是发布后，用命令 xxx.exe --urls "http://*:5000"  会报错
![image](https://github.com/nacos-group/nacos-sdk-csharp/assets/38172595/3e549229-ecc4-4e6c-91c8-5abc9a482421)

## Related code

```JSON
 "nacos": {
    "Namespace": "1fc842aa-5e0b-41ca-a406-4ee1fb49f7c8", // Please set the value of Namespace ID !!!!!!!!
    "ServerAddresses": [ "http://192.168.133.170:8848" ],
    "UserName": "nacos",
    "Password": "nacos",
    "EndPoint": "",
    "DefaultTimeOut": 15000,
    "ListenInterval": 1000,
    "ServiceName": "IotCloud-Service",
    "GroupName": "DEFAULT_GROUP",
    "Ip": "",
    "PreferredNetworks": "", // select an IP that matches the prefix as the service registration IP
    "Port": 0,
    "Weight": 100,
    "RegisterEnabled": true,
    "InstanceEnabled": true,
    "Ephemeral": true,

    "ConfigUseRpc": true,
    "NamingUseRpc": true,
    "NamingLoadCacheAtStart": "",
    "LBStrategy": "WeightRandom", //WeightRandom WeightRoundRobin
    "Metadata": {
    }
  }
```

```csharp
 //服务注册
        services.AddNacosAspNet(App.Configuration, "nacos");
```

## Tell us your environment

- nacos-sdk-csharp version: [e.g. 1.13.5/...]
- modular : [e.g. naming/config/msconfig/....]
- nacos server version: [e.g. 2.1.1/....]
- how to host nacos server : [e.g. docker...]

**Comment by zhanglilong23** [comment]
var config = app.Configuration;
var urls = config.GetSection("Urls")?.Value; 
Console.WriteLine("启动urls: " + urls);
app.Run(string.IsNullOrWhiteSpace(urls) ? "http://*:5005" : urls);

在Program启动页，app.Run() 增加urls读取配置。 这样无论是默认配置，还是使用--urls命令，都可以读取到。
注意，如果读取到的Urls是分号分割的多个地址，Nacos注册可能会报错，所以最好指定单个Urls值，比如配置到appsetting.json中。

**Comment by zhanglilong23** [comment]
邮件已收到，我会尽快回复您。
