### ISSUE TITLE
使用0.8.5版本SDK，注册到nacos的IP为127.0.0.1

### ISSUE THREAD

**Issue by little-cui** [nacos-group/nacos-sdk-csharp#254]
## Describe what happened (or what feature you want)

A clear and concise description of what happened or what you want.

使用0.8.5版本SDK，注册到nacos的实例IP为127.0.0.1，请问这是什么原因？
升级到1.3.4版本SDK，就可以显示正确的IP信息。

## Tell us your environment

- nacos-sdk-csharp version: 0.8.5
- modular : naming
- nacos server version: 2.1.0
- how to host nacos server : k8s

**Comment by catcherwong** [comment]
参考一下 #106 

一般获取到 127.0.0.1 就是没能成功获取到IP，降级到 127.0.0.1 了。
