### ISSUE TITLE
M1芯片 nacos服务注册失败

### ISSUE THREAD

**Issue by odinsam** [nacos-group/nacos-sdk-csharp#255]
nacos版本 2.23 单机启动
Net Core 配置
```json
"nacos": {
    "EndPoint": "",
    "ServerAddresses": [ "http://localhost:8848/" ],
    "DefaultTimeOut": 15000,
    "Namespace": "0414bb69-4853-425d-89dc-988e9ef592f5",  // 这里请设置 Namespace ID 的值!!!!!!!!
    "ListenInterval": 1000,
    "ServiceName": "App1",
    "GroupName": "DEFAULT_GROUP",
    "ClusterName": "DEFAULT",
    "Ip": "localhost",
    "PreferredNetworks": "", // select an IP that matches the prefix as the service registration IP
    "Port": 5212,
    "Weight": 100,
    "RegisterEnabled": true,
    "InstanceEnabled": true,
    "Ephemeral": true,
    "Secure": false,
    "AccessKey": "",
    "SecretKey": "",
    "UserName": "",
    "Password": "",
    "ConfigUseRpc": true,
    "NamingUseRpc": true,   //  NamingUseRpc 改为false  则可以成功注册
    "NamingLoadCacheAtStart": "",
    "LBStrategy": "WeightRandom", //WeightRandom WeightRoundRobin
    "Metadata": {
      "aa": "bb",
      "cc": "dd"
    }
  }
```
报错信息
fail: Nacos.AspNetCore.V2.RegSvcBgTask[0]
      register instance error, count = 3
      Nacos.V2.Exceptions.NacosException: Request nacos server failed: -401, Client not connected,current status: STARTING
         at Nacos.V2.Naming.Remote.Grpc.NamingGrpcClientProxy.RequestToServer[T](AbstractNamingRequest request)
         at Nacos.V2.Naming.Remote.Grpc.NamingGrpcClientProxy.DoRegisterService(String serviceName, String groupName, Instance instance)
         at Nacos.V2.Naming.Remote.Grpc.NamingGrpcClientProxy.RegisterServiceAsync(String serviceName, String groupName, Instance instance)
         at Nacos.V2.Naming.Remote.NamingClientProxyDelegate.RegisterServiceAsync(String serviceName, String groupName, Instance instance)
         at Nacos.V2.Naming.NacosNamingService.RegisterInstance(String serviceName, String groupName, Instance instance)
         at Nacos.AspNetCore.V2.RegSvcBgTask.StartAsync(CancellationToken cancellationToken)

**Comment by odinsam** [comment]
windows系统就没有任何问题

**Comment by heqingpan** [comment]
.net core sdk不支持m1芯片的原因是因为sdk grpc底层使用的是Grpc.Core，Grpc.Core不支持macOS arm64芯片。

Grpc.Core不支持macOS arm64的原因是因为：Grpc.Core依赖native动态库，然后Grpc.Core包中没有macOS arm64对应的动态库。（windows支持x86和x64,linux支持x64和arm64,macOS只支持x64）


解决方案：

1. 联系Grpc.Core开发者，让其发布支持macOS arm64的新版本；目前Grpc.Core已不更新，其推荐使用grpc-dotnet。
2. 使用grpc-dotnet替换Grpc.Core ，我在本地测试grpc-dotnet的例子，其打包出的结果不依赖native动态库，也就没有grpc-dotnet的问题。 

我看 #258 也有讨论切换到grpc-dotnet，Grpc.Core已不更新，切换到grpc-dotnet的方案应该更合适一些。

----

Grpc.Core不支持macOS arm64，从应用发布结果就能看出来。

使用当前仓库的[samples/App3](https://github.com/nacos-group/nacos-sdk-csharp/tree/dev/samples/App3)例子，在`samples/App3`目录下执行发布命令`dotnet publish`,在 public目录下有runtimes native 动态库包，有5类动态库，不包含osx-arm64 。

发布包文件夹下具体的文件信息如下：

```
$ tree .
.
├── App3
├── App3.deps.json
├── App3.dll
├── App3.pdb
├── App3.runtimeconfig.json
├── App3.xml
├── Google.Protobuf.dll
├── Grpc.Core.Api.dll
├── Grpc.Core.dll
├── Microsoft.Extensions.DependencyModel.dll
├── Nacos.AspNetCore.dll
├── Nacos.AspNetCore.pdb
├── Nacos.AspNetCore.xml
├── Nacos.dll
├── Nacos.pdb
├── Nacos.xml
├── Newtonsoft.Json.dll
├── appsettings.Development.json
├── appsettings.json
├── runtimes
│   ├── linux-arm64
│   │   └── native
│   │       └── libgrpc_csharp_ext.arm64.so
│   ├── linux-x64
│   │   └── native
│   │       └── libgrpc_csharp_ext.x64.so
│   ├── osx-x64
│   │   └── native
│   │       └── libgrpc_csharp_ext.x64.dylib
│   ├── win-x64
│   │   └── native
│   │       └── grpc_csharp_ext.x64.dll
│   └── win-x86
│       └── native
│           └── grpc_csharp_ext.x86.dll
└── web.config


```

**Comment by chenhaoqwe** [comment]
我也是同样的问题，是因为苹果系统这样吗？
