### ISSUE TITLE
ServerListManager访问serverlist出现404

### ISSUE THREAD

**Issue by Xishang7707** [nacos-group/nacos-sdk-csharp#257]
Nacos 2.2.3
sdk 1.3.5

**Comment by catcherwong** [comment]
具体的错误日志可以贴一下吗？

**Comment by Xishang7707** [comment]
![image](https://github.com/nacos-group/nacos-sdk-csharp/assets/38380429/ceb52c10-3786-4323-bbbf-c33bdc391faa)

StatusCode: 404, ReasonPhrase: '', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Vary: Origin
  Vary: Access-Control-Request-Method
  Vary: Access-Control-Request-Headers
  Content-Security-Policy: script-src 'self'
  Transfer-Encoding: chunked
  Date: Tue, 18 Jul 2023 00:58:55 GMT
  Content-Type: application/json
}, Trailing Headers:
{
}

**Comment by Xishang7707** [comment]
> 具体的错误日志可以贴一下吗？
nacos配置那块是正常的，应该不存在部署问题

**Comment by RoyLi-Pvt** [comment]
SDK不支持单节点模式?我这边测试Nacos单节点模式下这个地址就是返回404

**Comment by catcherwong** [comment]
EndPoint 一般会配合地址服务一起使用，从地址服务返回 nacos server 的IP信息
