### ISSUE TITLE
配置读取不出来都是null 

### ISSUE THREAD

**Issue by lzhisgood** [nacos-group/nacos-sdk-csharp#259]
{
  "NacosConfig": {
    "Listeners": [
      {
        "Optional": false,
        "DataId": "common",
        "Group": "DEFAULT_GROUP"
      }
    ],
    "Optional": false,
    "Namespace": "命名空间id",
    "ServerAddresses": [ "mse-a4dfdb40-p.nacos-ans.mse.aliyuncs.com:8848" ],
    "UserName": "nacos",
    "Password": "nacos",
    "AccessKey": "",
    "SecretKey": "",
    "EndPoint": "mse-a4dfdb40-p.nacos-ans.mse.aliyuncs.com",
    "ConfigFilterAssemblies": [ "MsConfigApp" ],
    "ConfigFilterExtInfo": "{\"JsonPaths\":[\"ConnectionStrings.Default\"],\"Other\":\"xxxxxx\"}"
  }
}
‘服务端用的阿里云的微服务引擎’
username  和 password怎么设置的啊，有没相应的文档这些节点什么意思，按照控制台提供的nodejs一样的配置就能读取到，net 为什么不行啊，配置就是上面发的

**Comment by catcherwong** [comment]
mse 不用配置 username 和 password

另外 endpoint 也是不需要的
