### ISSUE TITLE
某些1.0版本的服务需要更新到2.0的路由

### ISSUE THREAD

**Issue by gainorloss** [nacos-group/nacos-sdk-csharp#267]
## Describe what happened (or what feature you want)
NacosNamingService.GetServiceOfServer 版本升级v2.0 /nacos/v1/ns/service/list=>/nacos/v2/ns/service/list
A clear and concise description of what happened or what you want.

## Related code

```JSON
{
}
```

```csharp
services.Addxxxxx

builder.Addxxxx
```

## Tell us your environment

- nacos-sdk-csharp version: [e.g. 1.1.0/...]
- modular : [e.g. naming/config/msconfig/....]
- nacos server version: [e.g. 2.0.0/....]
- how to host nacos server : [e.g. docker/k8s/mse/virtual machine/...]

**Comment by gainorloss** [comment]
该接口当前访问404,server版本2.2.3,追源码，配置和服务的版本号都是常量统一定义的 不知道修改这里会不会导致其他服务不可用。该bug是在 yarp集成nacos的示例中 发现的，每次轮询该接口都会报404 取不到服务，无法正常生成Yarp配置[](https://github.com/catcherwong-archive/2021/tree/main/YarpWithNacosSample)

**Comment by catcherwong** [comment]
如果 nacos server 是2.x，建议 **NamingUseRpc** 设置成 true，这样sdk和server 是用 grpc 通讯的，就不用管 http 相关的接口。

**Comment by gainorloss** [comment]
我来试下

**Comment by catcherwong** [comment]
ServerAddress不用改，服务端要开放 9848 的端口

**Comment by gainorloss** [comment]
我这边是容器内模拟的环境，我这边再配置使用rpc之后所有接口都连不上了，我来查查看看是咋回事，另外这个http接口的问题，我能帮什么忙吗

**Comment by gainorloss** [comment]
报了个错：Nacos.V2.Naming.NacosNamingService[0]       [SecurityProxy] login http request failed, url: http://nacos-server:8848/nacos/v1/auth/users/login       System.Net.Http.HttpRequestException: Name or service not known (nacos-server:8848)       
![image](https://github.com/nacos-group/nacos-sdk-csharp/assets/26458238/f0639b6f-80c5-45c7-9f87-9a1ca7b870e7)

**Comment by catcherwong** [comment]
Name or service not known (nacos-server:8848)

这个很明显是解析不了这个域名。

**Comment by catcherwong** [comment]
> 这个http接口的问题，我能帮什么忙吗

这个理论上不用处理。

**Comment by gainorloss** [comment]
> Name or service not known (nacos-server:8848)
> 
> 这个很明显是解析不了这个域名。

一开始启动的时候 估计是nacos容器未完全启动，后边过了一会，连上了

**Comment by gainorloss** [comment]
> > 这个http接口的问题，我能帮什么忙吗
> 
> 这个理论上不用处理。服务端是同时支持 v1 和 v2 的
在服务端的文档中貌似有看到说是向前兼容的，看样子现在最稳妥的方式是全部使用 _**rpc**_ 了吧
