### ISSUE TITLE
接入nacos客户端导致webapi接口时不时就卡顿 

### ISSUE THREAD

**Issue by qiangboy** [nacos-group/nacos-sdk-csharp#280]
一接入nacos就会导致接口随机一段时间出现卡顿，500ms-8000ms之间，去掉nacos客户端，一切正常！！！接入nacos会影响http请求的管道？有点不可思议!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by catcherwong** [comment]
如果可以，箐提供一个最小化的可以复现问题的sample。

另外，server 和 sdk 的版本是多少。

**Comment by qiangboy** [comment]
> 如果可以，箐提供一个最小化的可以复现问题的sample。
> 
> 另外，server 和 sdk 的版本是多少。

[项目地址：](https://github.com/qiangboy/NacosTest.git)
在centos8中启动docker-compose，使用的nacos版本是2.1.0

1.新建命名空间和配置
![0C7E8ACF-E740-4ba4-BD3F-18E43BAC6212](https://github.com/nacos-group/nacos-sdk-csharp/assets/44226864/dbf4e540-b74b-4baa-bd18-a90fba63064e)

![EF12FEE9-0527-4486-8148-E71918266362](https://github.com/nacos-group/nacos-sdk-csharp/assets/44226864/d47b5f3e-85fa-4b03-b898-fdd44be4cbff)

2.重启webapi的容器

3.调用接口测试
![D4E5084C-764C-4a9c-BE4E-3B50BCE93729](https://github.com/nacos-group/nacos-sdk-csharp/assets/44226864/4d36d167-792a-453d-922f-8858caffccb3)

一般等待几分钟就会出现卡的情况，如果把nacos的服务注册发现和配置中心都去掉，测试了一天，超过300ms的情况为0

**Comment by qiangboy** [comment]
![4FAFB142-7E25-4768-A2B6-E2926B2C297E](https://github.com/nacos-group/nacos-sdk-csharp/assets/44226864/29d36186-adc3-4425-a278-7cfceef58f2e)

**Comment by Memoyu** [comment]
实际运行下来发现没有很大的波动的
![8a54c5365e1dfb880d1ba2de6619096](https://github.com/nacos-group/nacos-sdk-csharp/assets/33112476/97c67608-a125-4dd3-a349-8798de9893a3)

**Comment by qiangboy** [comment]
> 实际运行下来发现没有很大的波动的 ![8a54c5365e1dfb880d1ba2de6619096](https://user-images.githubusercontent.com/33112476/282741822-97c67608-a125-4dd3-a349-8798de9893a3.png)

测试的是linux系统的吗？我在windows本地运行webapi程序，然后也运行了一个windows的nacos，是测不出来顿卡的情况的

**Comment by Memoyu** [comment]
> > 实际运行下来发现没有很大的波动的 ![8a54c5365e1dfb880d1ba2de6619096](https://user-images.githubusercontent.com/33112476/282741822-97c67608-a125-4dd3-a349-8798de9893a3.png)
> 
> 测试的是linux系统的吗？我在windows本地运行webapi程序，然后也运行了一个windows的nacos，是测不出来顿卡的情况的

那这看起来也不像是sdk的问题，我再继续观察一下😏

**Comment by qiangboy** [comment]
> > > 实际运行下来发现没有很大的波动的 ![8a54c5365e1dfb880d1ba2de6619096](https://user-images.githubusercontent.com/33112476/282741822-97c67608-a125-4dd3-a349-8798de9893a3.png)
> > 
> > 
> > 测试的是linux系统的吗？我在windows本地运行webapi程序，然后也运行了一个windows的nacos，是测不出来顿卡的情况的
> 
> 那这看起来也不像是sdk的问题，我再继续观察一下😏

不好说，或许是sdk在linux会出现这种状况？但也想不通，sdk应该没对请求管道做什么操作吧？

**Comment by qiangboy** [comment]
换成consul了，流畅得狠，美滋滋
