### ISSUE TITLE
.net core 7 如何在Startup获取Nacos的配置

### ISSUE THREAD

**Issue by ChiMuYao-GitHub** [nacos-group/nacos-sdk-csharp#286]
![1701658386205](https://github.com/nacos-group/nacos-sdk-csharp/assets/152829995/a39d8667-6a5e-4296-8646-c258d0475c45)

**Comment by Memoyu** [comment]
也许你可以参考一下这个：
[Samples/MsConfigApp](https://github.com/nacos-group/nacos-sdk-csharp/blob/dev/samples/MsConfigApp/Program.cs)
![image](https://github.com/nacos-group/nacos-sdk-csharp/assets/33112476/29e9bc37-dc9e-4708-af24-9814751eaf6f)
