### ISSUE TITLE
how to update instance metadata

### ISSUE THREAD

**Issue by muistar** [nacos-group/nacos-sdk-csharp#289]
INacosNamingService no UpdateInstance func，INamingClientProxy have a UpdateInstance func，Calling through reflection often fails to respond。

// INacosNamingService 接口未提供更新方法，INamingClientProxy 提供了，但是INamingClientProxy 在INacosNamingService 是私有的，通过反射去调用UpdateInstance更新元数据时，偶尔有反应(很久才会更新)，一般情况下都没反应。

**Comment by catcherwong** [comment]
一般只有在运维侧(控制台)才会去改 metadata 吧， sdk 侧也需要直接改？

**Comment by muistar** [comment]
> 一般只有在运维侧(控制台)才会去改 metadata 吧， sdk 侧也需要直接改？

正常情况是使用静态的metadata，我这边是想尝试弄动态的metadata(例如cpu占用、内存占用)，其他服务监听到通过metadata的自定义数据做负载...  想偷个懒不自己做^_^
