### ISSUE TITLE
一个nacos的配置错误会引起整个服务程序的奔溃

### ISSUE THREAD

**Issue by kuyz123** [nacos-group/nacos-sdk-csharp#291]
例如：我的nacos配置json如： {“a”:您好}，实时上“您好” 是少了两个双引号的，会导致整个服务奔溃。问题可以重现，理论应该是某个配置错误不应该影响整体服务程序。希望加一个try...catch,来捕获错误异常。

**Comment by catcherwong** [comment]
如果你的配置不是必须的，考虑把下面这个设置成 true.

https://github.com/nacos-group/nacos-sdk-csharp/blob/7664d2d36afbfcbbb3929a6aa0ceb3dd3392658b/samples/MsConfigApp/appsettings.json#L5

**Comment by kuyz123** [comment]
谢谢
