### ISSUE TITLE
使用samples中的MsConfigApp应用，启动异常，NacosV2ConfigurationProvider中数据类型转换失败

### ISSUE THREAD

**Issue by JaneConan** [nacos-group/nacos-sdk-csharp#301]
## Describe what happened (or what feature you want)

使用samples中的MsConfigApp应用，启动异常

## Describe what you expected to happen

NacosV2ConfigurationProvider中数据类型转换失败

## Related code

```JSON
{
  "NacosConfig": {
    "Listeners": [
      {
        "Optional": false,
        "DataId": "common",
        "Group": "DEFAULT_GROUP"
      },
      {
        "Optional": false,
        "DataId": "demo",
        "Group": "DEFAULT_GROUP"
      }
    ],
    "Optional": false,
    "Namespace": "cs",
    "ServerAddresses": [ "http://localhost:8848/" ],
    "UserName": "",
    "Password": "",
    "AccessKey": "",
    "SecretKey": "",
    "EndPoint": "acm.aliyun.com",
    "ConfigFilterAssemblies": [ "MsConfigApp" ],
    "ConfigFilterExtInfo": "{\"JsonPaths\":[\"ConnectionStrings.Default\"],\"Other\":\"xxxxxx\"}"
  }
}

```

```csharp
services.Addxxxxx

builder.Addxxxx
```

## Tell us your environment

- nacos-sdk-csharp version: [e.g. 1.1.0/...]
- modular : [e.g. naming/config/msconfig/....]
- nacos server version: [e.g. 2.0.0/....]
- how to host nacos server : [e.g. docker/k8s/mse/virtual machine/...]

## Anything else we need to know?

![image](https://github.com/user-attachments/assets/beefb78a-48ff-46b2-b78e-9f7d9330508c)

**Comment by Memoyu** [comment]
这个是因为client无法读取到服务端配置项抛出的异常，你确认一下nacos服务端中是否已存在对应配置：` dataid=common, group=DEFAULT_GROUP, tenant=cs`
