### ISSUE TITLE
配置文件用户名和密码加密

### ISSUE THREAD

**Issue by Amber-Wish** [nacos-group/nacos-sdk-csharp#303]
由于Nacos 服务只能由部分同事访问并管理，所以配置文件中的用户名和密码明文显示，则无法保护nacos服务。
请问这有什么解决方法吗

**Comment by Memoyu** [comment]
> 由于Nacos 服务只能由部分同事访问并管理，所以配置文件中的用户名和密码明文显示，则无法保护nacos服务。 请问这有什么解决方法吗

这按理说不应该由client进行处理，毕竟密文的账号密码在使用时解密仍然需要使用密钥，密钥又需要配置；
感觉可以使用占位符，如下配置，在CICD脚本中进行关键字替换，然后在自动化部署工具中进行nacos账户管理：
```json
{
  "NacosConfig": {
    ...
    "UserName": "{Nacos_UserName}",
    "Password": "{Nacos_Password}",
    ...
  }
}
```

**Comment by lianghao620** [comment]
请问 本地开发怎么办？还是得 把 账号密码写在appsettings 中

**Comment by Memoyu** [comment]
> 请问 本地开发怎么办？还是得 把 账号密码写在appsettings 中

本地开发那只能是配置明文了，如同数据库、Redis配置等
