### ISSUE TITLE
容器化运行.Net6, 多个DataId 程序会卡住不动，不能注册服务

### ISSUE THREAD

**Issue by MagicPurple7** [nacos-group/nacos-sdk-csharp#307]
## Describe what happened (or what feature you want)
在Docker/K8s中运行.net6程序时，当Listeners 数组长度大于等于3时，程序会被卡住没有报错，也没有注册服务到nacos。
如下图：
![image](https://github.com/user-attachments/assets/9b95242b-bb55-4f0e-b4f5-a08833101e70)
分别测试过Listeners数组长度 为1和2的情况，是可以正常运行，并注册服务到nacos的。
nacos 环境是：版本2.4.0 + k8s 单副本部署
请问有遇到这种情况的大佬吗？有解决方案可以分享吗？

**Comment by wutao0315** [comment]
代码bug 死循环。在修复#293的时候触发的新bug
由于本地没有缓存文件的时候会向 _listenExecutebell添加数据
private readonly BlockingCollection<object> _listenExecutebell = new BlockingCollection<object>(boundedCapacity: 1);
 而另一个线程消费的时候又会通过调用NotifyListenConfig触发向 _listenExecutebell 添加数据，导致完全阻塞。
 if (hasChangedKeys)
      await NotifyListenConfig().ConfigureAwait(false);

**Comment by wutao0315** [comment]
在删除本地缓存文件(nacos)的时候会立即触发，容器容易触发是因为容器每次都没有这个缓存所以一定触发

**Comment by Memoyu** [comment]
> 在删除本地缓存文件(nacos)的时候会立即触发，容器容易触发是因为容器每次都没有这个缓存所以一定触发

😂感谢反馈，这就调整

**Comment by MagicPurple7** [comment]
@Memoyu 大佬，请问这个bug预计什么时候发sdk修复版？

**Comment by catcherwong** [comment]
Released  v1.3.8

**Comment by MagicPurple7** [comment]
nice working!
