### ISSUE TITLE
INacosNamingService如何获取实时的在nacos的注册服务及服务实例

### ISSUE THREAD

**Issue by caesarhub73** [nacos-group/nacos-sdk-csharp#309]
## Describe what happened (or what feature you want)

在使用GetServicesOfServer或者GetAllInstances时没办法获取到实时的服务信息或者服务的实例信息，会有5-40s的延迟。

## Describe what you expected to happen

能够无延迟的获取到nacos上注册的服务和服务实例，而不是从缓存中读取（会有延迟）。

## Tell us your environment

- nacos-sdk-csharp version: [1.3.5]
- nacos server version: [2.4.0]

**Comment by caesarhub73** [comment]
@catcherwong 如没有配置直接走api获取服务和实例的参数麻烦请回复，且关闭issue，我将自行实现。谢谢

**Comment by catcherwong** [comment]
你说的这两个方法，都是实时调API接口或gRPC方法去获取的，sdk这边是没有做缓存的。

**Comment by caesarhub73** [comment]
我做了一个对比sdk和调用api的获取service和instance的测试。

**Comment by caesarhub73** [comment]
我做了一个对比sdk和调用api的获取service和instance的测试。
1.服务注册到nacos，sdk使用INacosNamingService.SelectInstances("serviceName",true),api使用nacos/v2/ns/instance/list进行http请求。对服务实例进行上下线操作，前几次sdk和api获取实例一样，当次数多了之后sdk与api获取的实例就不一样了，下线的服务实例sdk也可以获取到。
![image](https://github.com/user-attachments/assets/f117ee7e-53d4-4503-a1b8-43f7ddbe8d60)

**Comment by caesarhub73** [comment]
2.服务注册到nacos。将服务实例下线后且把服务从后台关闭，重新将服务开启并注册到nacos后，nacos的服务状态为下线，但是sdk依然可以获取到该实例。

**Comment by caesarhub73** [comment]
3.服务注册到nacos，先多次对服务实例进行上下线操作，让sdk与api获取到的实例不一致后停止操作。等待35秒后两个sdk与api获取实例一致。
![image](https://github.com/user-attachments/assets/6ba95dd0-46f2-487e-a397-4f4415692def)
![image](https://github.com/user-attachments/assets/7d6b370c-b8c0-4e17-8f7a-d5cf458b48c2)

**Comment by caesarhub73** [comment]
@catcherwong 没有用gRPC，用的是http。有把sdk引用到服务然后跟过一次代码，但是没太明白是为什么。猜测是因为缓存。如果有空且有需要可以看一下这个问题，使用sdk还得额外的调用api挺奇怪的哈哈哈哈哈哈

**Comment by Memoyu** [comment]
> @catcherwong 没有用gRPC，用的是http。有把sdk引用到服务然后跟过一次代码，但是没太明白是为什么。猜测是因为缓存。如果有空且有需要可以看一下这个问题，使用sdk还得额外的调用api挺奇怪的哈哈哈哈哈哈

目前sdk内部确实是没有做缓存的；
你可以尝试启用一下gRPC，试试是否还存在问题；
`sdk还得额外的调用api` 不调用api你怎么实现交互呢？莫非还有别的方案？

**Comment by caesarhub73** [comment]
> > @catcherwong 没有用gRPC，用的是http。有把sdk引用到服务然后跟过一次代码，但是没太明白是为什么。猜测是因为缓存。如果有空且有需要可以看一下这个问题，使用sdk还得额外的调用api挺奇怪的哈哈哈哈哈哈
> 
> 目前sdk内部确实是没有做缓存的； 你可以尝试启用一下gRPC，试试是否还存在问题； `sdk还得额外的调用api` 不调用api你怎么实现交互呢？莫非还有别的方案？

`sdk还得额外的调用api` 我的意思是如果要实时获取实例的话要走nacos的接口。
我应该是找到原因了。Task<List<Instance>> SelectInstances(string serviceName, bool healthy, bool subscribe);subscribe默认是true，会触发定时任务去跑实例而不是直接走nacos的api获取实例。定时任务会放到ServiceInfoHolder的_serviceInfoMap里面，获取的时候是从内存里里面取的，所以会有延迟。subscribe设置为false就好了。

**Comment by caesarhub73** [comment]
谢谢支持
