### ISSUE TITLE
The registered IP address was wrong, it was 127.0.0.1

### ISSUE THREAD

**Issue by CarsonFjz** [nacos-group/nacos-sdk-csharp#32]
希望能改成这种获取方法       
Nacos.AspNetCore/StatusReportBgTask.cs

        private string GetCurrentIp()
        {
            var instanceIp = "127.0.0.1";

            // 获取说有网卡信息
            NetworkInterface[] nics = NetworkInterface.GetAllNetworkInterfaces();
            foreach (NetworkInterface adapter in nics)
            {
                // 判断是否为以太网卡
                if (adapter.NetworkInterfaceType == NetworkInterfaceType.Ethernet)
                {
                    // 获取以太网卡网络接口信息
                    IPInterfaceProperties ip = adapter.GetIPProperties();
                    UnicastIPAddressInformationCollection ipCollection = ip.UnicastAddresses;
                    foreach (UnicastIPAddressInformation ipadd in ipCollection)
                    {
                        Console.WriteLine(ipadd.Address.ToString());
                        if (ipadd.Address.AddressFamily == AddressFamily.InterNetwork)
                        {
                            if (string.IsNullOrEmpty(_options.PreferredNetworks))
                            {
                                return ipadd.Address.ToString();
                            }
                        }
                    }
                }
                else if (adapter.NetworkInterfaceType == NetworkInterfaceType.Wireless80211)
                {
                    // 获取无线网卡接口信息
                    IPInterfaceProperties ip = adapter.GetIPProperties();
                    UnicastIPAddressInformationCollection ipCollection = ip.UnicastAddresses;
                    foreach (UnicastIPAddressInformation ipadd in ipCollection)
                    {
                        Console.WriteLine(ipadd.Address.ToString());
                        if (ipadd.Address.AddressFamily == AddressFamily.InterNetwork)
                        {
                            if (!ipadd.ToString().StartsWith(_options.PreferredNetworks))
                                return ipadd.Address.ToString();
                        }
                    }
                }
            }

            return instanceIp;
        }

**Comment by catcherwong** [comment]
@CarsonFjz  谢谢您对这个项目感兴趣！

可以的，您方便提个PR过来吗？

-------

Thanks for your interest in this project.

Looks good,  could you please submit a PR?

**Comment by catcherwong** [comment]
The code seems can not get a right IP address as well.

![image](https://user-images.githubusercontent.com/8394988/91625497-7303e980-e9da-11ea-909b-d601ac2e0d4d.png)

**Comment by catcherwong** [comment]
Ref #36
