### ISSUE TITLE
How to implement loading the configuration from multi-files and share the configuration

### ISSUE THREAD

**Issue by xujiesh0510** [nacos-group/nacos-sdk-csharp#38]
请问  Nacos配置的多文件加载与共享配置  这个有计划做么？
java 的spring 里面已经实现了。
https://www.jianshu.com/p/0dde1ae350c4

------

Is there any plans on loading the configuration from multi-files and share the configuration.

The Spring framework has implemented it.

**Comment by catcherwong** [comment]
@xujiesh0510 谢谢您对这个项目感兴趣！

看了一下您发的文章，也大致知道您这边的需求。这个功能可能需要讨论一下，再决定是否加入计划中。

-------

Thanks for your interest in this project.

After reading the article, I also know the requirements of your side. This feature may need to be discussed before deciding whether to join the plan.

**Comment by xujiesh0510** [comment]
感谢。

**Comment by xujiesh0510** [comment]
看到了新的提交了，请问现在进展怎么样？

**Comment by catcherwong** [comment]
.NET Core的配置集成已经支持 多个 dataid 和 group 的组合了。近期会发布一个预览版。

--------

The integration of .NET Core configuration is supporting multi dataid and group. We will release a preview version for it.

https://github.com/nacos-group/nacos-sdk-csharp/blob/f8114fc1bd21dc6e52711bf1abe430b25d4f09d9/samples/MsConfigApp/appsettings.json#L3-L14

**Comment by catcherwong** [comment]
We have released v0.8.0. This version supports listen multiple configuration/share configuration.

You can have a look on this [README file](https://github.com/nacos-group/nacos-sdk-csharp/blob/v0.8.0/samples/MsConfigApp/README.md) to get more information, and have a try with this feature.

**Comment by xujiesh0510** [comment]
greate work ! thanks
