### ISSUE TITLE
In k8s, the port is fixed and IP is acquired automatically

### ISSUE THREAD

**Issue by amwitx** [nacos-group/nacos-sdk-csharp#45]
In k8s, the port is fixed and IP is acquired automatically
It is suggested to add some codes
In the uritool class

......
// 1. config
if (!string.IsNullOrWhiteSpace(config.Ip))
{
	// it seems that nacos don't return the scheme
	// so here use http only.
	return new Uri($"http://{config.Ip}:{port}");
}

**// 1.1. Ip is null && Port has value
if (string.IsNullOrWhiteSpace(config.Ip) && port != 80)
{
	return new Uri($"http://{GetCurrentIp(config.PreferredNetworks)}:{port}");
}**

var address = string.Empty;

// 2. IServerAddressesFeature
if (features != null)
{
......

thanks！！！

**Comment by catcherwong** [comment]
@amwitx  Thanks for your interest in this project.

LGTM! Could you submit a PR to fix this issue?

**Comment by catcherwong** [comment]
v0.8.0 done this issue. Please have a try with it.
