### ISSUE TITLE
nuget ver 0.5  appsetting PreferredNetworks not work

### ISSUE THREAD

**Issue by dazhu6666** [nacos-group/nacos-sdk-csharp#46]
**set  PreferredNetworks 192.168.0 , the client log is** 

 Sending HTTP request PUT http://192.168.0.149:8848/nacos/v1/ns/instance/beat?serviceName=DEMO-USER-SERVICE&beat={"port":5050,"ip":"127.0.0.1","weight":100.0,"serviceName":"DEMO-USER-SERVICE","cluster":null,"metadata":{"preserved.register.source":"ASPNET_CORE"},"scheduled":true,"period":0,"stopped":false}&namespaceId=e37a2391-aa65-4774-9c21-c1a11e4523ce&ephemeral=True&groupName=aicloudview-dev-group&app=MicroService

**use the github source code is correct**

 Sending HTTP request PUT http://192.168.0.149:8848/nacos/v1/ns/instance/beat?serviceName=DEMO-USER-SERVICE&beat={"port":5050,"ip":"192.168.0.170","weight":100.0,"serviceName":"DEMO-USER-SERVICE","cluster":null,"metadata":{"preserved.register.source":"ASPNET_CORE"},"scheduled":true,"period":0,"stopped":false}&namespaceId=e37a2391-aa65-4774-9c21-c1a11e4523ce&ephemeral=True&groupName=aicloudview-dev-group&app=MicroService

**Comment by catcherwong** [comment]
@dazhu6666 Thanks for your interest in this project.

We will release v0.8.0 to fixed this bug later this week.

**Comment by catcherwong** [comment]
v0.8.0 was released to nuget.

Please have a try with it.
