### ISSUE TITLE
 There is a problem with samples-msconfiapp v0.8.0

### ISSUE THREAD

**Issue by lijingpan** [nacos-group/nacos-sdk-csharp#51]
![20201027102308](https://user-images.githubusercontent.com/10410600/97249237-6ebf4580-183e-11eb-8d48-b3fea3eda8db.png)

![1_20201027102343](https://user-images.githubusercontent.com/10410600/97249321-957d7c00-183e-11eb-930b-0f288d6c2498.png)

don't know how to configure it？

**Comment by catcherwong** [comment]
@lijingpan Thanks for your interest in this project.

For msconfigapp, [AppSettings.cs](https://github.com/nacos-group/nacos-sdk-csharp/blob/master/samples/MsConfigApp/AppSettings.cs) contains some information of the configuration.

You can modify it to take a look on what will happen.

BTW, if the configuration can map your DTO class, you can use `Options` mode to read the configuration.

If not, you can use `IConfiguration`  to  read the configuration.
