### ISSUE TITLE
怎么配置当前服务不向注册中心注册

### ISSUE THREAD

**Issue by lijingpan** [nacos-group/nacos-sdk-csharp#52]
你好，请问是否有 registerEnabled 的配置，我看了源码没有找到。

**Comment by catcherwong** [comment]
@lijingpan 谢谢您对这个项目感兴趣！

这个暂时没有呢，是出于什么原因想不向注册中心注册呢？

**Comment by lijingpan** [comment]
> @lijingpan 谢谢您对这个项目感兴趣！
> 
> 这个暂时没有呢，是出于什么原因想不向注册中心注册呢？

用grpc 写了一个服务器注册进去，Client端不想注册进去，只想纯粹的调用服务。是否有解决方案

**Comment by catcherwong** [comment]
知道需求了，目前这个还不支持。

如果您有时间的话，可以提个PR来支持这个功能。

我这边估计要到双11之后才会有时间处理。

**Comment by catcherwong** [comment]
试试最新预览版。加了一个RegisterEnabled的配置，把它设置成false就可以了。

https://github.com/nacos-group/nacos-sdk-csharp/blob/f58657a8d1867420dc7fc540dbe970395bb92289/samples/App1/appsettings.json#L8-L15

**Comment by lijingpan** [comment]
非常感谢

> 试试最新预览版。加了一个RegisterEnabled的配置，把它设置成false就可以了。
> 
> https://github.com/nacos-group/nacos-sdk-csharp/blob/f58657a8d1867420dc7fc540dbe970395bb92289/samples/App1/appsettings.json#L8-L15

非常感谢
