### ISSUE TITLE
只能获取一条配置信息吗？

### ISSUE THREAD

**Issue by caopengfei** [nacos-group/nacos-sdk-csharp#53]
tenant、dataId、group都放在了配置文件里面，那就是说整个项目只能获取一个配置信息吗？那我如果要在不同的位置使用不同的配置，那怎么处理呢？只能将所有的配置信息放到一个大的配置里去么？

**Comment by catcherwong** [comment]
@caopengfei 谢谢您对这个项目感兴趣！

v0.8.0支持读取同一个namespace下面的多条配置信息， 参见  https://github.com/nacos-group/nacos-sdk-csharp/blob/master/samples/MsConfigApp/README.md
