### ISSUE TITLE
Array can not be modified correctly

### ISSUE THREAD

**Issue by dingjason** [nacos-group/nacos-sdk-csharp#56]
原始配置如下，
![image](https://user-images.githubusercontent.com/4499763/99045986-170a3380-25cd-11eb-99c5-8b3e1cc8e2ba.png)
修改AppSettings:Arr的值为[0,1]后，程序里获取到的值为[0,1,3]。
查看源码应该是回调这里有问题
![image](https://user-images.githubusercontent.com/4499763/99046670-0dcd9680-25ce-11eb-999f-a07a12e8d8e6.png)
经过解析，数组的key为：AppSettings:Arr:0、AppSettings:Arr:1、AppSettings:Arr:2，经过修改后，AppSettings:Arr:2的值并没有被删除

nacos版本1.3.1，驱动版本0.8.0

**Comment by catcherwong** [comment]
@dingjason Thanks for your interest in this project.

We will take a look ASAP for this problem. I have reproduced it.

**Comment by catcherwong** [comment]
Have a try with the last preview version.

**Comment by dingjason** [comment]
I have tried the last version, it works well👌.
