### ISSUE TITLE
在K8S环境中ip不固定，端口是可以固定的，而且会非80的情况，所以在UriTool勒种增加了加粗部分

### ISSUE THREAD

**Issue by amwitx** [nacos-group/nacos-sdk-csharp#61]
在K8S环境中ip不固定，端口是可以固定的，而且会非80的情况，所以在UriTool勒种增加了加粗部分
之前的逻辑是，要么端口ip都设置，要么都不设置，这个是有问题的
// 1. config
if (!string.IsNullOrWhiteSpace(config.Ip))
{
	// it seems that nacos don't return the scheme
	// so here use http only.
	return new Uri($"http://{config.Ip}:{port}");
}

**// 1.1. Ip is null && Port has value
if (string.IsNullOrWhiteSpace(config.Ip) && port != 80)
{
	return new Uri($"http://{GetCurrentIp(config.PreferredNetworks)}:{port}");
}**

var address = string.Empty;

// 2. IServerAddressesFeature
if (features != null)
{
   ...

**Comment by catcherwong** [comment]
Duplicate, see #45 .
