### ISSUE TITLE
在控制台程序中，开启状态报告报错，增加参数控制是否需要开启状态报告

### ISSUE THREAD

**Issue by amwitx** [nacos-group/nacos-sdk-csharp#62]
public static IServiceCollection AddNacosAspNetCore(
	this IServiceCollection services,
	IConfiguration configuration,
	**bool isReport = true**)
{
	....

// IHostedService, report instance status
**if (isReport)**
{
services.AddHostedService< StatusReportBgTask>();
}

return services;
}

使用时
services.AddNacosAspNetCore(Configuration, **false**);

**Comment by catcherwong** [comment]
@amwitx 谢谢您对这个项目感兴趣！

看一下您是不是想要  #52  的效果?

**Comment by amwitx** [comment]
是的 谢谢

**Comment by amwitx** [comment]
发现最新的0.8.0的代码并没有增加

**Comment by catcherwong** [comment]
目前还是预览版。正式版还没有这个。

**Comment by catcherwong** [comment]
已经发布0.8.5 正式版本。
