### ISSUE TITLE
HttpClient 使用有问题

### ISSUE THREAD

**Issue by wapco** [nacos-group/nacos-sdk-csharp#64]
发现代码中大量用到using(var client = new HttpClient())，这种写法可能会有问题。可以看一下这篇文章：https://www.cnblogs.com/jlion/p/12813692.html

**Comment by catcherwong** [comment]
通用逻辑上会用到直接new。

如果直接注入IHttpClientFactory，会不利于集成.NET Core自带的配置。

**Comment by wapco** [comment]
那建议用单例的HttpClient，不然new太多的HttpClient得不到释放，会导致系统socket资源浪费

**Comment by catcherwong** [comment]
Version 1.0.0 done it. 😄
