### ISSUE TITLE
设置了Namespace和GroupName后发现会有问题

### ISSUE THREAD

**Issue by tonghu007** [nacos-group/nacos-sdk-csharp#65]
设置了Namespace和GroupName后，注册到Nacos中的服务总是时断时续，不设置Namespace和GroupName的情况下没有问题。

**Comment by catcherwong** [comment]
请问是如何使用的，用的sdk是那个版本，nacos server是那个版本？

**Comment by tonghu007** [comment]
sdk是最新的，nacos 是2.0.0，默认的namespace和groupname没问题，但是如果指定了，注册到nacos中的服务就一时连上，一时断开了

**Comment by catcherwong** [comment]
看上去是获取服务的时候出问题了，方便的话贴一下日志。

目前nacos-sdk-csharp还没有发布nuget包可以直接对接nacos 2.0，可以用dev分支的代码做测试。

**Comment by catcherwong** [comment]
没有回应，先关闭，后续有问题的话请重新打开或提交一个新的。
