### ISSUE TITLE
请问GRPC支持吗？应该如何配置呢？

### ISSUE THREAD

**Issue by tonghu007** [nacos-group/nacos-sdk-csharp#66]
请问GRPC支持吗？应该如何配置呢？

**Comment by catcherwong** [comment]
支持grpc是指对接 nacos 2.0 还是其他？

**Comment by tonghu007** [comment]
是这样的，grpc的服务注册到nacos2.0上会有两个不同端口，但是服务的名字是一样的，而用INacosServerManager通过GetServerAsync取到的地址两个端口的地址都有（应该是根据负载均衡返回的地址吧），而有个端口请求grpc是不行的。所以不知道这个地方该怎么用，不好意思，刚开始学grpc，也不知道是不是配置得有问题。

**Comment by catcherwong** [comment]
是一个服务，暴露一个grpc的端口和一个http的端口吗？

如果是多个端口，可以用metadata存储更多的信息，把grpc的端口放在metadata里面。

**Comment by tonghu007** [comment]
不好意思，可能可以处理，我创建的GRPC项目默认加了两个地址，我以为必须两个，去掉一个好像也没问题，那就应该是没问题了，谢谢
