### ISSUE TITLE
_serverManager.GetServerAsync("demoService") 取不到服务地址

### ISSUE THREAD

**Issue by tonghu007** [nacos-group/nacos-sdk-csharp#67]
_serverManager.GetServerAsync("demoService") 取不到服务地址，Nacos里面是有demoService服务的，InstanceId为null引起的，报错如下：
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Nacos.AspNetCore
  StackTrace:
   at Nacos.AspNetCore.WeightRandomLBStrategy.<>c__DisplayClass2_0.<GetHost>b__0(Host x)

**Comment by catcherwong** [comment]
请问用的sdk是那个版本，nacos server是那个版本？

**Comment by tonghu007** [comment]
sdk 是用的最新的，nacos用的是2.0.0

**Comment by tonghu007** [comment]
WeightRandomLBStrategy.cs 文件第24行x.InstanceId是null，我是把代码clone下来改了下才能用的

**Comment by catcherwong** [comment]
Have a try with version 1.0.0. 😄
