### ISSUE TITLE
UriTool.GetUri获取地址的问题

### ISSUE THREAD

**Issue by leili-ncut** [nacos-group/nacos-sdk-csharp#68]
目前实现的测试：
1. IServerAddressesFeature中一直拿不到uri
2. Environment.GetEnvironmentVariable能拿到环境变量中的配置，没有的话会返回默认值
3. Environment.GetCommandLineArgs 拿命令行参数 
建议：
1. 命令行的优先级最高，修改下获取的顺序

**Comment by catcherwong** [comment]
> 1. IServerAddressesFeature中一直拿不到uri

您是在本地调试的时候拿不到吗？是的话，可以参考一下 https://github.com/catcherwong/nacos-sdk-csharp/issues/2

> 4. 命令行的优先级最高，修改下获取的顺序

这个顺序要讨论一下才会决定是否要调整。

**Comment by leili-ncut** [comment]
谢谢回复， 对于问题1，我本地测试环境是 as.net core 3.1,GetUri中的addresses?.Addresses拿到的是空。

**Comment by catcherwong** [comment]
暂时没收到其他反馈，先关了这个issue，如果有其他问题可以重新打开或新开一个issue
