### ISSUE TITLE
SaveSnapshotAsync方法有bug

### ISSUE THREAD

**Issue by wapco** [nacos-group/nacos-sdk-csharp#69]
using (FileStream fs = new FileStream(snapshotFile.FullName, FileMode.OpenOrCreate, FileAccess.Write, FileShare.ReadWrite))
                {
                    byte[] bytes = Encoding.UTF8.GetBytes(config);
                    fs.SetLength(bytes.Length);
                    await fs.WriteAsync(bytes, 0, bytes.Length);
                    fs.Close();
                }

这里应该添加fs.SetLength(bytes.Length);否则如果配置文件内容变短了，后面的文本没被清空。其他3个地方也是一样的问题。

**Comment by catcherwong** [comment]
Have a try with version 1.0.0. 😄
