### ISSUE TITLE
How to run the application in IIS

### ISSUE THREAD

**Issue by zengcooper** [nacos-group/nacos-sdk-csharp#7]
![image](https://user-images.githubusercontent.com/45378354/88034413-3b9c5480-cb73-11ea-89fb-f5937005fba0.png)
当部署到iis或者iis express上面时，注册nacos控件会报错！

**Comment by zengcooper** [comment]
如果用 kestrel运行就没有这个问题!! 不知道大家有没有相关得解决方案

**Comment by catcherwong** [comment]
@zengcooper  谢谢您对这个项目感兴趣！

没有试过在IIS上面部署，如果要在Windows上面部署，可以试试Windows服务。

------

Thanks for your interest in this project.

I don't host .NET Core projects on IIS. But if you want to host in Windows, you can use Windows Service.

**Comment by kookpua** [comment]
我在iis上部署是可以的,不过会触发保护阈值  不稳定
`"nacos": {
    "ServerAddresses": [ "http://192.168.128.241:8848" ],
    "DefaultTimeOut": 15000,
    "Namespace": "",
    "ListenInterval": 1000,
    "ServiceName": "Promotion",
    "Ip": "192.168.135.26",
    "Port": 5000
  }`

**Comment by catcherwong** [comment]
@kookpua  

您的请求量很大吗？应该不会触发保护阈值吧？您这边有试过Windows服务的方式吗？

最新版的`nacos-sdk-csharp` 是已经没有 `app.UseNacosAspNetCore()` 这个方法了。


------

Are your requests large? Shouldn't the protection threshold be triggered? Have you tried the Windows service?

The latest version of `nacos-sdk-csharp` does not have the `app.UseNacosAspNetCore()` method.

**Comment by kookpua** [comment]
> @kookpua
> 
> 您的请求量很大吗？应该不会触发保护阈值吧？您这边有试过Windows服务的方式吗？
> 
> 最新版的`nacos-sdk-csharp` 是已经没有 `app.UseNacosAspNetCore()` 这个方法了。
> 
> Are your requests large? Shouldn't the protection threshold be triggered? Have you tried the Windows service?
> 
> The latest version of `nacos-sdk-csharp` does not have the `app.UseNacosAspNetCore()` method.

没有请求量,只是刷新下nacos的服务列表就变红了(连的公司的内部nacos服务器),

nacos服务器和服务都在我本地的时候没问题

**Comment by kookpua** [comment]
@catcherwong   

sorry,刚刚又试了下,好了

服务器把nacos版本从1.3.0升级到1.3.1 ok了,

我在本地用1.2和1.3.1都好着,服务器是1.3.0不行

所以这个问题是nacos1.3.0的bug吗 哈哈

**Comment by catcherwong** [comment]
Closed! Have any question, reopen or open a new one.
