### ISSUE TITLE
运行你的samples

### ISSUE THREAD

**Issue by GerryGithub1** [nacos-group/nacos-sdk-csharp#74]
![image](https://user-images.githubusercontent.com/44516088/108722526-3b779380-755e-11eb-9568-c39632aeec27.png)
上图中InsatanceId为空，故出现空指针，我把Item.key放到Equals前面没有问题，还请大佬订正下

**Comment by catcherwong** [comment]
您下载的是那个版本呢？

**Comment by GerryGithub1** [comment]
2.0的Nacos

**Comment by GerryGithub1** [comment]
然后我也更新了 你最新的1.0.0那个版本 还是出现同样的问题。发现也没有你sample提供的V2下面API

**Comment by catcherwong** [comment]
用的那个nuget包，新版是把 unofficial 移除了的。

https://github.com/nacos-group/nacos-sdk-csharp/blob/dev/docs/zh-cn/%E5%8D%87%E7%BA%A7%E5%88%B01.0%E7%89%88%E6%9C%AC%E6%8C%87%E5%BC%95.md

**Comment by catcherwong** [comment]
先关闭这个ISSUE了，如果还有问题，请重新打开或者开一个新的。
