### ISSUE TITLE
版本0.8.0注册服务失败

### ISSUE THREAD

**Issue by LightCHY** [nacos-group/nacos-sdk-csharp#75]
![image](https://user-images.githubusercontent.com/18217025/109151588-538d2400-77a5-11eb-9cf6-3bbd387344f2.png)
当字典中的kv数据大于1时注册会报错：failed to req API:/nacos/v1/ns/instance after all servers

**Comment by catcherwong** [comment]
@LightCHY  谢谢您对这个项目感兴趣。

麻烦升级到最新版本试试。

**Comment by LightCHY** [comment]
@catcherwong 谢谢您的回答。
已升到1.0版本，但异常照旧，翻看了Nacos中的日志：
![image](https://user-images.githubusercontent.com/18217025/109596519-61e69180-7b51-11eb-9a28-99464b7cd77b.png)
是由该方法报出：
![image](https://user-images.githubusercontent.com/18217025/109596569-7c206f80-7b51-11eb-8010-85cf550552e7.png)

**Comment by catcherwong** [comment]
版本 `1.0.1-alpha20210302115432.nupkg`  修复了这个问题，你可以再试试。

**Comment by LightCHY** [comment]
1.0.1-alpha20210302115432.nupkg 这个在哪儿获取到？nuget上未看到有该版本

**Comment by LightCHY** [comment]
噢，找到了,跑这个下面了：nacos-sdk-csharp.IniParser

**Comment by LightCHY** [comment]
噢，找到了,跑这个下面了：nacos-sdk-csharp.IniParser，测试通过了。
