### ISSUE TITLE
建议独立2.0分支

### ISSUE THREAD

**Issue by leyou240** [nacos-group/nacos-sdk-csharp#77]
如题，没必要继续在当前分支开发。nacos2.0服务端也是一个独立的分支。
代码都放一起，阅读起来不太方便呀。

**Comment by catcherwong** [comment]
@leyou240 谢谢您对这个项目感兴趣！

独立分支最后都是会合并回主分支的，客户端这边不只是要支持2.0的服务端，1.x的服务端也是要考虑的。

2.0对接的目前都在V2的目录下面。
