### ISSUE TITLE
关于帮助文档

### ISSUE THREAD

**Issue by HaoLi-Rainbow** [nacos-group/nacos-sdk-csharp#78]
nacos server: 1.4.1
这个文档太含糊了，如果只想要将我的服务注册到nacos上，那我到底要添加什么代码呢？
望作者解答，谢谢

**Comment by pins-cn** [comment]
> # 能不能写一个实例呢？
README  文件上写得很清楚
使用V2版本 在Startup. ConfigureServices内写services.AddNacosAspNet(Configuration);
![image](https://user-images.githubusercontent.com/80266774/110477736-7e209a80-811e-11eb-83b5-eaa1a3d6c13b.png)
appsettings.json 加入 以下配置是Http服务
  "nacos": {
    "ServerAddresses": [ "http://localhost:8848" ],
    "DefaultTimeOut": 15000,
    "ListenInterval": 1000,
    "ServiceName": "NacosGateway",
    "GroupName": "Sample",
    "Namespace": "",
    "NamingUseRpc": false
  }
![image](https://user-images.githubusercontent.com/80266774/110478005-cdff6180-811e-11eb-8155-d78f116f2c33.png)
