### ISSUE TITLE
注册到nacos0.9.0报错

### ISSUE THREAD

**Issue by caopengfei** [nacos-group/nacos-sdk-csharp#86]
使用的包为nacos-sdk-csharp.AspNetCore，版本：1.0.2
配置文件为：
`
{
  "nacos": {
    "ServiceName": "parkingIot",
    "ServerAddresses": [ "http://x.x.x.x:8848" ],
    "DefaultTimeOut": 5000,
    "Namespace": "",
    "ListenInterval": 1000,
    "GroupName": "DEFAULT_GROUP",
    "ClusterName": "DEFAULT",
    "Ip": "172.18.75.22",
    "PreferredNetworks": "", // select an IP that matches the prefix as the service registration IP
    "Port": 8020,
    "Weight": 100,
    "RegisterEnabled": true,
    "InstanceEnabled": true,
    "Ephemeral": true,
    "Secure": false,
    "AccessKey": "",
    "SecretKey": "",
    "UserName": "",
    "Password": "",
    "ConfigUseRpc": false,
    "NamingUseRpc": false,
    "NamingLoadCacheAtStart": "",
    "LBStrategy": "WeightRandom", //WeightRandom WeightRoundRobin
	"Metadata": {
      "version": "V1.1.1.0"
    }
  }
}
`
报错信息为：
`
fail: Nacos.V2.Naming.NacosNamingService[0]
      request: /nacos/v1/ns/instance/beat failed, servers: http://x.x.x.x:8848, code: 500, msg: BadRequest
fail: Nacos.V2.Naming.NacosNamingService[0]
      [CLIENT-BEAT] failed to send beat: BeatInfo{port=8020, ip='172.18.75.22', weight=100, serviceName='DEFAULT_GROUP@@parkingIot', cluster='DEFAULT', metadata={"preserved.register.source":"ASPNET_CORE","DOTNET_VERSION":"5.0.4","HOST_OS":"Unix 3.10.0.693","version":"V1.1.1.0"}, scheduled=False, period=5000, stopped=False}, code: 500, msg: failed to req API: /nacos/v1/ns/instance/beat after all servers(System.Collections.Generic.List`1[System.String]) tried: BadRequest
      Nacos.V2.Exceptions.NacosException: failed to req API: /nacos/v1/ns/instance/beat after all servers(System.Collections.Generic.List`1[System.String]) tried: BadRequest
         at Nacos.V2.Naming.Remote.Http.NamingHttpClientProxy.ReqApi(String url, Dictionary`2 paramters, Dictionary`2 body, List`1 servers, HttpMethod method)
         at Nacos.V2.Naming.Remote.Http.NamingHttpClientProxy.ReqApi(String url, Dictionary`2 paramters, Dictionary`2 body, HttpMethod method)
         at Nacos.V2.Naming.Remote.Http.NamingHttpClientProxy.SendBeat(BeatInfo beatInfo, Boolean lightBeatEnabled)
         at Nacos.V2.Naming.Beat.BeatReactor.BeatTask(BeatInfo beatInfo)
`

**Comment by catcherwong** [comment]
这个是服务端 报 500 了， 建议 nacos 服务端还是升级到 1.x 或者是 2.0。

这个 sdk 开始写的时候， 貌似是基于 1.x 的， 没有对 0.x 进行兼容
