### ISSUE TITLE
ServerAddresses 乱填也不报错

### ISSUE THREAD

**Issue by zlzforever** [nacos-group/nacos-sdk-csharp#88]
1. 按示例配置好后，获取不到配置
2. 经测试发现 ServerAddresses 我乱填也不报错
3. 我通过 curl -X GET 'http://xxx.com/nacos/v1/cs/configs?dataId=dev-wms-api&group=DEFAULT_GROUP&tenant=a83b5c88-77ad-46b9-bae7-c4dce91d6a64  可以获取配置

现在我不知道怎么定位问题了...

**Comment by catcherwong** [comment]
> 按示例配置好后，获取不到配置

方便提供一下使用的nacos-server和sdk的版本吗? 

> 经测试发现 ServerAddresses 我乱填也不报错

方便提供一下去掉敏感信息的配置吗

**Comment by catcherwong** [comment]
ServerAddresses 这个问题是因为 Failover 机制，不会因为请求服务端失败就抛出异常，还会去本地获取缓存，如果缓存也没有的话会返回空。

这个 异常 可以在日志里面看到：

如果是 2.x 的话会看到   Client not connected,current status: 2

如果是 1.x 的话会看到   No such host is known

**Comment by zlzforever** [comment]
1. docker 部署的 nacos/nacos-server:2.0.0-bugfix  版本
2. sdk 是nuget 上的最新版 1.0.2

我没有看到任何异常信息，日志也没有。

```
{
  "NacosConfig": {
    "Listeners": [
      {
        "Optional": false,
        "DataId": "dev-wms-api",
        "Group": "DEFAULT_GROUP"
      }
    ],
    "Tenant": "a83b5c88-77ad-46b9-bae7-c4dce91d6a64",
    "ServerAddresses": [
      "http://xxxxx.com"
    ],
    "UserName": "nacos",
    "Password": "xxxxxxx",
    "AccessKey": "",
    "SecretKey": "",
    "EndPoint": ""
  }
}
```

**Comment by fadyxu** [comment]
这个示例确定能跑通吗，GetSection("NacosConfig")是空，估计其他人拿不到配置也是这个原因

**Comment by catcherwong** [comment]
经了解，您那边部署是用域名的，没有暴露出端口，会导致计算偏移量无法对应上真正的nacos服务端实例的grpc服务端口。详见 [Nacos 2.0.0 兼容性文档](https://nacos.io/en-us/docs/2.0.0-compatibility.html)

所以您可以暂时设置 `"ConfigUseRpc": false` 走http协议，不走grpc协议。

集成包的日志问题，已经发布 `1.0.3-alpha20210417150732` ，这个版本会在控制台输出日志。
