### ISSUE TITLE
NacosSdkOptions 中 EndPoint 作用

### ISSUE THREAD

**Issue by YinHaoDev** [nacos-group/nacos-sdk-csharp#92]
"nacos": {
    "EndPoint": "sub-domain.aliyun.com:8080"
  }

能详细介绍一下这个属性的作用范围吗？

**Comment by catcherwong** [comment]
Nacos集群部署模式有 **直连模式** 、 **VIP 模式** 和 **地址服务器模式**。

`ServerAddresses` 这个配置项是针对  **直连模式** 和  **VIP 模式** 的。

`EndPoint` 这个配置项是针对  **地址服务器模式** 的。

可以参考下面这个文章：

https://zhuanlan.zhihu.com/p/341950456
