### ISSUE TITLE
无法注册持久化实例

### ISSUE THREAD

**Issue by sicongHe** [nacos-group/nacos-sdk-csharp#95]
刚刚开始研究Nacos结合.net core做服务注册发现，遇到了这样一个问题：
在appsettings.json中配置了 "Ephemeral":false 但是在nacos中显示的实例一直是临时实例，不知道问题出在哪里呢？望指教
![image](https://user-images.githubusercontent.com/17338308/117644311-eee64080-b1bb-11eb-8bf6-4e7873e5b36b.png)
![image](https://user-images.githubusercontent.com/17338308/117644562-2d7bfb00-b1bc-11eb-8b10-2df0d93f68d5.png)

**Comment by sicongHe** [comment]
所以目前无法通过配置的方式注册持久化实例了是吗？

**Comment by catcherwong** [comment]
是的，长链接的方式，不允许注册持久化实例了。

**Comment by catcherwong** [comment]
2.0的服务注册这一块还有支持 HTTP接口的，HTTP接口是兼容之前的版本。

把 `NamingUseRpc` 设为false，就不会用grpc和服务端通信，而是用http和服务端通信。

**Comment by sicongHe** [comment]
懂了！感谢耐心解答～
